\documentclass[
  man,
  floatsintext,
  longtable,
  nolmodern,
  notxfonts,
  notimes,
  colorlinks=true,linkcolor=blue,citecolor=blue,urlcolor=blue]{apa7}

\usepackage{amsmath}
\usepackage{amssymb}




\RequirePackage{longtable}
\RequirePackage{threeparttablex}

\makeatletter
\renewcommand{\paragraph}{\@startsection{paragraph}{4}{\parindent}%
	{0\baselineskip \@plus 0.2ex \@minus 0.2ex}%
	{-.5em}%
	{\normalfont\normalsize\bfseries\typesectitle}}

\renewcommand{\subparagraph}[1]{\@startsection{subparagraph}{5}{0.5em}%
	{0\baselineskip \@plus 0.2ex \@minus 0.2ex}%
	{-\z@\relax}%
	{\normalfont\normalsize\bfseries\itshape\hspace{\parindent}{#1}\textit{\addperi}}{\relax}}
\makeatother




\usepackage{longtable, booktabs, multirow, multicol, colortbl, hhline, caption, array, float, xpatch}
\usepackage{subcaption}


\renewcommand\thesubfigure{\Alph{subfigure}}
\setcounter{topnumber}{2}
\setcounter{bottomnumber}{2}
\setcounter{totalnumber}{4}
\renewcommand{\topfraction}{0.85}
\renewcommand{\bottomfraction}{0.85}
\renewcommand{\textfraction}{0.15}
\renewcommand{\floatpagefraction}{0.7}

\usepackage{tcolorbox}
\tcbuselibrary{listings,theorems, breakable, skins}
\usepackage{fontawesome5}

\definecolor{quarto-callout-color}{HTML}{909090}
\definecolor{quarto-callout-note-color}{HTML}{0758E5}
\definecolor{quarto-callout-important-color}{HTML}{CC1914}
\definecolor{quarto-callout-warning-color}{HTML}{EB9113}
\definecolor{quarto-callout-tip-color}{HTML}{00A047}
\definecolor{quarto-callout-caution-color}{HTML}{FC5300}
\definecolor{quarto-callout-color-frame}{HTML}{ACACAC}
\definecolor{quarto-callout-note-color-frame}{HTML}{4582EC}
\definecolor{quarto-callout-important-color-frame}{HTML}{D9534F}
\definecolor{quarto-callout-warning-color-frame}{HTML}{F0AD4E}
\definecolor{quarto-callout-tip-color-frame}{HTML}{02B875}
\definecolor{quarto-callout-caution-color-frame}{HTML}{FD7E14}

%\newlength\Oldarrayrulewidth
%\newlength\Oldtabcolsep


\usepackage{hyperref}




\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\usepackage{longtable,booktabs,array}
\usepackage{calc} % for calculating minipage widths
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}

\usepackage{graphicx}
\makeatletter
\newsavebox\pandoc@box
\newcommand*\pandocbounded[1]{% scales image to fit in text height/width
  \sbox\pandoc@box{#1}%
  \Gscale@div\@tempa{\textheight}{\dimexpr\ht\pandoc@box+\dp\pandoc@box\relax}%
  \Gscale@div\@tempb{\linewidth}{\wd\pandoc@box}%
  \ifdim\@tempb\p@<\@tempa\p@\let\@tempa\@tempb\fi% select the smaller of both
  \ifdim\@tempa\p@<\p@\scalebox{\@tempa}{\usebox\pandoc@box}%
  \else\usebox{\pandoc@box}%
  \fi%
}
% Set default figure placement to htbp
\def\fps@figure{htbp}
\makeatother


% definitions for citeproc citations
\NewDocumentCommand\citeproctext{}{}
\NewDocumentCommand\citeproc{mm}{%
  \begingroup\def\citeproctext{#2}\cite{#1}\endgroup}
\makeatletter
 % allow citations to break across lines
 \let\@cite@ofmt\@firstofone
 % avoid brackets around text for \cite:
 \def\@biblabel#1{}
 \def\@cite#1#2{{#1\if@tempswa , #2\fi}}
\makeatother
\newlength{\cslhangindent}
\setlength{\cslhangindent}{1.5em}
\newlength{\csllabelwidth}
\setlength{\csllabelwidth}{3em}
\newenvironment{CSLReferences}[2] % #1 hanging-indent, #2 entry-spacing
 {\begin{list}{}{%
  \setlength{\itemindent}{0pt}
  \setlength{\leftmargin}{0pt}
  \setlength{\parsep}{0pt}
  % turn on hanging indent if param 1 is 1
  \ifodd #1
   \setlength{\leftmargin}{\cslhangindent}
   \setlength{\itemindent}{-1\cslhangindent}
  \fi
  % set entry spacing
  \setlength{\itemsep}{#2\baselineskip}}}
 {\end{list}}
\usepackage{calc}
\newcommand{\CSLBlock}[1]{\hfill\break\parbox[t]{\linewidth}{\strut\ignorespaces#1\strut}}
\newcommand{\CSLLeftMargin}[1]{\parbox[t]{\csllabelwidth}{\strut#1\strut}}
\newcommand{\CSLRightInline}[1]{\parbox[t]{\linewidth - \csllabelwidth}{\strut#1\strut}}
\newcommand{\CSLIndent}[1]{\hspace{\cslhangindent}#1}


\usepackage[nolongtablepatch]{lineno}
\linenumbers



\usepackage{newtx}

\defaultfontfeatures{Scale=MatchLowercase}
\defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}





\title{Mapping the Structure of Executive Function in Early Childhood
using Network Analysis}


\shorttitle{Mapping Executive Function}


\usepackage{etoolbox}









\authorsnames[{1,2},{2},{3},{4},{5},{3},{2},{2}]{A,B,C,D,E,F*,G*,H*}







\authorsaffiliations{
{Stanford University},{University of Oxford},{University of the
Witwatersrand},{University of Kentucky},{University of California,
Davis}}




\leftheader{A, B, C, D, E, F*, G* and H*}



\abstract{TO BE ADDED. }

\keywords{executive function}

\authornote{ 

\par{   The author has no conflict of interest to declare. This work was
supported by X.   }
\par{Correspondence concerning this article should be addressed
to A, Email: \href{mailto:f@psy.ox.ac.uk}{f@psy.ox.ac.uk}}
}

\makeatletter
\let\endoldlt\endlongtable
\def\endlongtable{
\hline
\endoldlt
}
\makeatother

\urlstyle{same}



\usepackage{setspace}
% \AtBeginEnvironment{longtable}{\singlespacing\footnotesize}
\AtBeginEnvironment{longtable}{\singlespacing\renewcommand*{\arraystretch}{1.15}}
\usepackage{booktabs}
\usepackage{caption}
\usepackage{longtable}
\usepackage{colortbl}
\usepackage{array}
\usepackage{anyfontsize}
\usepackage{multirow}
\makeatletter
\@ifpackageloaded{caption}{}{\usepackage{caption}}
\AtBeginDocument{%
\ifdefined\contentsname
  \renewcommand*\contentsname{Table of contents}
\else
  \newcommand\contentsname{Table of contents}
\fi
\ifdefined\listfigurename
  \renewcommand*\listfigurename{List of Figures}
\else
  \newcommand\listfigurename{List of Figures}
\fi
\ifdefined\listtablename
  \renewcommand*\listtablename{List of Tables}
\else
  \newcommand\listtablename{List of Tables}
\fi
\ifdefined\figurename
  \renewcommand*\figurename{Figure}
\else
  \newcommand\figurename{Figure}
\fi
\ifdefined\tablename
  \renewcommand*\tablename{Table}
\else
  \newcommand\tablename{Table}
\fi
}
\@ifpackageloaded{float}{}{\usepackage{float}}
\floatstyle{ruled}
\@ifundefined{c@chapter}{\newfloat{codelisting}{h}{lop}}{\newfloat{codelisting}{h}{lop}[chapter]}
\floatname{codelisting}{Listing}
\newcommand*\listoflistings{\listof{codelisting}{List of Listings}}
\makeatother
\makeatletter
\usepackage{pdflscape}
\makeatother
\makeatletter
\makeatother
\makeatletter
\@ifpackageloaded{caption}{}{\usepackage{caption}}
\@ifpackageloaded{subcaption}{}{\usepackage{subcaption}}
\makeatother

% From https://tex.stackexchange.com/a/645996/211326
%%% apa7 doesn't want to add appendix section titles in the toc
%%% let's make it do it
\makeatletter
\xpatchcmd{\appendix}
  {\par}
  {\addcontentsline{toc}{section}{\@currentlabelname}\par}
  {}{}
\makeatother

%% Disable longtable counter
%% https://tex.stackexchange.com/a/248395/211326

\usepackage{etoolbox}

\makeatletter
\patchcmd{\LT@caption}
  {\bgroup}
  {\bgroup\global\LTpatch@captiontrue}
  {}{}
\patchcmd{\longtable}
  {\par}
  {\par\global\LTpatch@captionfalse}
  {}{}
\apptocmd{\endlongtable}
  {\ifLTpatch@caption\else\addtocounter{table}{-1}\fi}
  {}{}
\newif\ifLTpatch@caption
\makeatother

\begin{document}

\maketitle




\setlength\LTleft{0pt}

\resetlinenumber[1]



\section{Introduction}\label{introduction}

Executive functions (EFs) comprise a set of higher-order cognitive
control processes that enable goal-directed, flexible, and adaptive
behavior (\citeproc{ref-diamond2013executive}{Diamond, 2013}). These
processes, including inhibitory control, working memory, and cognitive
flexibility, support the regulation of attention, the maintenance and
manipulation of information, and the ability to shift between task
rules. Early childhood represents a period of particularly rapid growth
in these abilities, coinciding with substantial maturation of the neural
systems that underpin cognitive control
(\citeproc{ref-best2010developmental}{Best \& Miller, 2010};
\citeproc{ref-blair2016executive}{Blair, 2016};
\citeproc{ref-garon2008executive}{Garon et al., 2008}).

\subsection{Unity and Diversity of Executive
Function}\label{unity-and-diversity-of-executive-function}

A central question in executive function research concerns how executive
abilities are organised: do inhibitory control, working memory, and
cognitive flexibility reflect distinct cognitive systems, or are they
manifestations of a common control mechanism? The influential
unity/diversity framework proposed by Miyake et al.
(\citeproc{ref-miyake2000unity}{2000}) suggests an integrative account.
Using confirmatory factor analysis with adults, Miyake et al.
(\citeproc{ref-miyake2000unity}{2000}) demonstrated that shifting,
updating, and inhibition are moderately correlated yet separable
constructs, best characterized by three correlated latent factors rather
than a single unitary factor or independent processes. This work
established that executive functions exhibit both unity (shared
variance) and diversity (component-specific variance).

Subsequent refinements introduced nested or bifactor formulations in
which a Common EF factor captures shared variance across tasks, while
Updating-Specific and Shifting-Specific factors account for residual
variance unique to those domains
(\citeproc{ref-friedman2017unity}{Friedman \& Miyake, 2017}). Notably,
inhibition tasks load almost entirely on the Common EF factor,
suggesting that inhibitory control closely aligns with processes common
to executive regulation more broadly. Twin modelling further
demonstrated that the unity component of executive function is highly
heritable, reinforcing the notion of a biologically grounded common
control system (\citeproc{ref-friedman2008individual}{Friedman et al.,
2008}).

A central developmental question concerns when and how this
differentiated structure emerges. Do young children exhibit the same
unity-diversity organization observed in adults, or does executive
function become progressively more differentiated across development?

\subsection{Developmental Differentiation of Executive
Function}\label{developmental-differentiation-of-executive-function}

During the preschool years, empirical research predominantly supports a
unidimensional representation of EF, with performance across tasks best
explained by a single underlying construct
(\citeproc{ref-nelson2016structure}{Nelson et al., 2016};
\citeproc{ref-wiebe2008using}{Wiebe et al., 2008};
\citeproc{ref-willoughby2012measurement}{Willoughby et al., 2012};
\citeproc{ref-zelazo2016executive}{Zelazo et al., 2016}). This pattern
is consistent with theoretical perspectives suggesting that executive
processes are relatively undifferentiated in young children and
progressively become more distinct with maturation
(\citeproc{ref-lehto2003dimensions}{Lehto et al., 2003};
\citeproc{ref-miyake2000unity}{Miyake et al., 2000}). Recent
longitudinal and network analyses have provided converging evidence for
this developmental differentiation, showing that EF transitions from one
factor in early childhood to increasingly separable components by late
childhood and adolescence (\citeproc{ref-brydges2012unitary}{Brydges et
al., 2012}; \citeproc{ref-menu2024latent}{Menu et al., 2024};
\citeproc{ref-reilly2022developmental}{Reilly et al., 2022}). However,
several investigations with preschool-aged samples have documented
bifactor solutions wherein inhibitory control emerges as separable from
working memory and cognitive flexibility
(\citeproc{ref-lee2013developmental}{Lee et al., 2013};
\citeproc{ref-miller2012latent}{Miller et al., 2012};
\citeproc{ref-usai2014latent}{Usai et al., 2014}), suggesting that the
transition toward differentiation may begin earlier in some populations
or measurement contexts.

Systematic reviews have confirmed this developmental progression:
preschool samples frequently support unidimensional or two-factor
solutions, whereas school-age children and adults more consistently
exhibit three-factor or nested structures
(\citeproc{ref-karr2018unity}{Karr et al., 2018};
\citeproc{ref-lee2013developmental}{Lee et al., 2013}). These findings
have been interpreted as evidence for progressive differentiation of
executive processes, whereby initially unified control mechanisms become
increasingly specialized with maturation.

\subsection{Neural Architecture of Executive
Function}\label{neural-architecture-of-executive-function}

Neuroimaging research in adults has identified distributed brain
networks that support executive function across diverse task demands.
Two core control networks are central to executive processing: the
fronto-parietal network (FPN), comprising dorsolateral prefrontal
cortex, inferior and superior parietal lobules, and middle frontal
gyrus; and the cingulo-opercular network (CON), including dorsal
anterior cingulate cortex and bilateral anterior insula
(\citeproc{ref-dosenbach2008dual}{Dosenbach et al., 2008};
\citeproc{ref-niendam2012meta}{Niendam et al., 2012}). The FPN is
hypothesized to support trial-by-trial adaptive control, while the CON
is implicated in task-set maintenance and sustained control across
trials (\citeproc{ref-dosenbach2008dual}{Dosenbach et al., 2008}).

These networks demonstrate reliable activation across inhibition,
working memory, and shifting tasks, providing neural evidence for the
``unity'' component observed in behavioral models
(\citeproc{ref-engelhardt2019neural}{Engelhardt et al., 2019};
\citeproc{ref-niendam2012meta}{Niendam et al., 2012}). A meta-analysis
of 193 neuroimaging studies confirmed that a superordinate
fronto-cingulo-parietal network is consistently engaged across executive
function domains (\citeproc{ref-niendam2012meta}{Niendam et al., 2012}).

While shared networks support general executive control, meta-analytic
evidence also reveals component-specific neural signatures paralleling
the ``diversity'' observed in behavioral factor structures. Inhibition
tasks show strongly right-lateralized activation, particularly in right
inferior frontal gyrus and superior parietal cortex
(\citeproc{ref-rodriguez2022inhibition}{Rodrı́guez-Nieto et al., 2022};
\citeproc{ref-zhang2017large}{Zhang et al., 2017}). Working memory tasks
engage bilateral dorsolateral prefrontal and posterior parietal cortex,
with load-dependent increases in inferior frontal gyrus
(\citeproc{ref-rottschy2012modelling}{Rottschy et al., 2012}). Shifting
tasks show bilateral activation with notable engagement of striatal and
cerebellar regions
(\citeproc{ref-rodriguez2022inhibition}{Rodrı́guez-Nieto et al., 2022}).
Executive tasks thus recruit common control networks while
simultaneously engaging component-specific regions
(\citeproc{ref-collette2006exploration}{Collette et al., 2006};
\citeproc{ref-mckenna2017informing}{McKenna et al., 2017}), mirroring
nested-factor behavioral models wherein a Common EF factor coexists with
component-specific factors.

\subsection{Developmental Emergence of Executive
Networks}\label{developmental-emergence-of-executive-networks}

The neural networks supporting executive function undergo substantial
reorganization during childhood and adolescence. A pivotal finding from
developmental neuroimaging is that the core architecture of adult
executive networks is established by middle childhood, approximately age
8-10 years (\citeproc{ref-engelhardt2019neural}{Engelhardt et al.,
2019}). Using task-based fMRI in children aged 8-13 years, Engelhardt et
al. (\citeproc{ref-engelhardt2019neural}{2019}) demonstrated that brain
regions consistently engaged across shifting, updating, and inhibition
tasks closely corresponded to the FPN and CON networks identified in
adults. Critically, after network establishment, developmental
improvements in executive function from middle childhood through
adolescence appear to reflect quantitative strengthening of connectivity
within established networks rather than qualitative reorganization of
network architecture (\citeproc{ref-engelhardt2019neural}{Engelhardt et
al., 2019}).

However, earlier in development---during the preschool and early
childhood period---functional brain organization appears less
differentiated. Longitudinal fNIRS studies reveal that functional
connectivity within the frontoparietal network and default mode network
is associated with executive function abilities as early as age 3, but
the strength and organization of these connections undergo considerable
change across early childhood (\citeproc{ref-kelsey2025forming}{Kelsey
et al., 2025}). At age 3-4, children exhibit weaker frontal-frontal
interactions and less refined fronto-parietal connectivity compared to
older children (\citeproc{ref-buss2018changes}{Buss \& Spencer, 2018};
\citeproc{ref-fiske2019neural}{Fiske \& Holmboe, 2019}). By age 4-5,
children show strengthened neural connections and more efficient
fronto-parietal pathways, enabling improved performance on executive
tasks (\citeproc{ref-buss2018changes}{Buss \& Spencer, 2018};
\citeproc{ref-ezekiel2013dimensional}{Ezekiel et al., 2013}).

Developmental fMRI research consistently demonstrates progressive
strengthening of functional connectivity within task-relevant
fronto-parietal and fronto-striatal networks from childhood through
adolescence, accompanied by increasing differentiation of activation
patterns (\citeproc{ref-rubia2013functional}{Rubia, 2013}). Younger
children (ages 6-8) recruit prefrontal regions more diffusely and fail
to engage the full fronto-parietal network observed in adults, instead
showing more localized activation in ventrolateral PFC
(\citeproc{ref-crone2006neurocognitive}{Crone et al., 2006};
\citeproc{ref-o2008neurodevelopmental}{O'Hare et al., 2008}). With age,
there is progressive recruitment of DLPFC, posterior parietal cortex,
and strengthening of long-range fronto-parietal and fronto-cerebellar
connectivity (\citeproc{ref-o2008neurodevelopmental}{O'Hare et al.,
2008}; \citeproc{ref-rubia2013functional}{Rubia, 2013}).

Recent work applying network control theory demonstrates that structural
brain networks mature to allow more efficient transitions to
fronto-parietal activation states necessary for executive function, with
reduced energetic cost observed from childhood through early adulthood
(\citeproc{ref-cui2020optimization}{Cui et al., 2020}). This
developmental reduction in control energy is driven primarily by
decreased costs within the fronto-parietal system itself, particularly
in lateral PFC and middle cingulate cortex---regions critical for task
preparation, execution, and monitoring
(\citeproc{ref-cui2020optimization}{Cui et al., 2020}).

The developmental trajectory of neural network organization closely
parallels the behavioral differentiation of executive function
components. Just as behavioral factor analyses reveal increasing
differentiation from a unidimensional structure in early childhood to
separable components by late childhood
(\citeproc{ref-karr2018unity}{Karr et al., 2018}), neuroimaging evidence
suggests progressive functional specialization of brain regions
supporting executive control
(\citeproc{ref-johnson2011interactive}{Johnson, 2011};
\citeproc{ref-li2025structural}{Li et al., 2025}). In early childhood,
executive tasks recruit less specialized and more diffuse patterns of
activation; with maturation, regions within FPN and CON networks become
increasingly selective in their functional profiles, supporting the
emergence of distinct yet coordinated executive processes
(\citeproc{ref-fiske2019neural}{Fiske \& Holmboe, 2019};
\citeproc{ref-shanmugan2016neural}{Shanmugan \& Satterthwaite, 2016}).
This developmental specialization occurs through multiple
neurobiological mechanisms, including experience-dependent synaptic
pruning, myelination of long-range white matter tracts, and refinement
of functional connectivity patterns
(\citeproc{ref-baum2020development}{Baum et al., 2020};
\citeproc{ref-tamnes2017development}{Tamnes et al., 2017}). The
convergence of behavioral differentiation and neural specialization
underscores that the unity-diversity structure of executive function is
grounded in the developing architecture of distributed brain networks.

\subsection{Methodological Approaches to Studying Executive
Organization}\label{methodological-approaches-to-studying-executive-organization}

Latent variable methodologies have been central to advancing the
unity/diversity framework. By extracting shared variance across multiple
tasks, confirmatory factor analysis addresses the problem of task
impurity and isolates executive constructs from task-specific noise
(\citeproc{ref-karr2018unity}{Karr et al., 2018};
\citeproc{ref-wiebe2008using}{Wiebe et al., 2008}). This approach has
proven particularly valuable for developmental research, as it enables
comparison of factor structures across age groups while accounting for
measurement error and task-specific variance.

At the same time, latent modelling relies on specific assumptions about
how executive abilities are represented. Latent factors are inferred
from covariance among observed tasks, with shared variance attributed to
common underlying processes and residual variance treated as
task-specific or error-related
(\citeproc{ref-vandierendonck2021utility}{Vandierendonck, 2021}).
Although this framework has proven powerful, the factor structure
obtained can vary depending on task selection, performance indicators,
and analytic specification (\citeproc{ref-miller2012latent}{Miller et
al., 2012}), highlighting that latent representations are partially
shaped by methodological choices.

Importantly, latent models characterize executive organisation in terms
of shared variance explained by unobserved factors. They do not directly
model conditional dependencies among executive components themselves.
From a systems perspective, this distinction matters. If executive
control reflects coordinated activity within distributed neural
networks, then understanding how executive components directly relate to
one another may offer complementary insight beyond shared latent
variance.

Recent methodological developments have begun to bridge this gap. For
example, latent network approaches integrate structural equation
modelling with network analysis to examine how executive constructs
relate within a relational framework (\citeproc{ref-menu2024latent}{Menu
et al., 2024}). Such approaches reflect a broader shift toward viewing
cognitive abilities as interconnected systems rather than solely as
reflections of underlying factors. A network perspective that models
conditional associations among executive components offers a
systems-level complement to latent approaches, enabling direct
investigation of developmental change in executive architecture.

\subsection{The Present Study}\label{the-present-study}

The present study applies network analysis to examine the organization
of executive function in early childhood across two longitudinal cohorts
from Australia and South Africa. Using Bayesian Gaussian Graphical
Models, we estimate age-adjusted partial correlations among inhibitory
control, working memory, and cognitive flexibility---capturing the
direct conditional associations among EF components after accounting for
shared relationships and age-related variance. This network approach
enables us to investigate the relational architecture of executive
abilities, examining which components show direct coupling, how these
conditional associations change developmentally, and whether network
structure varies across sociocultural contexts and socioeconomic
environments.

Understanding how executive components are organized during early
development holds substantial implications. Network analysis can reveal
whether EF components function as tightly coupled systems or operate
more independently, informing both theoretical models of executive
development and the design of interventions. If components show strong
direct coupling, broad interventions targeting general executive control
may be most effective; if components are weakly connected, targeted
domain-specific training may be warranted
(\citeproc{ref-li2025structural}{Li et al., 2025}).

\subsubsection{Research Questions}\label{research-questions}

\textbf{Research Question 1 (Primary): EF Network Structure Within
Cohorts}\\
Within each cohort and wave, what is the age-adjusted EF
network---defined by partial correlations among working memory,
inhibition, and cognitive flexibility---and what do global strength and
expected influence indicate about overall connectivity and node
centrality?

\textbf{Research Question 2 (Primary): Developmental Change Within
Cohorts}\\
Within each cohort, do the EF conditional associations (partial
correlations) change across adjacent waves (AU: T1→T2→T3; SA: T1→T2),
and if so, which specific edges strengthen or weaken over time?

\textbf{Research Question 3 (Secondary): Cross-Cohort Comparisons}\\
At matched waves (T1 and T2), do AU and SA differ in EF conditional
associations, and do the cohorts show divergent developmental
trajectories from T1 to T2 (difference-in-differences)?

\textbf{Research Question 4 (Exploratory): Socioeconomic Moderation of
Network Structure}\\
Within each cohort, does EF network structure differ between children
from high versus low baseline (T1) household income and home learning
environments? Specifically, are edges systematically stronger or weaker
in high-SES groups across waves?

\clearpage

\section{Methods}\label{methods}

\subsection{Participants}\label{participants}

\subsubsection{Australia}\label{australia}

Request description from Steven - unsure which paper this sample is
from.

\subsubsection{South Africa}\label{south-africa}

The South African sample was drawn from a longitudinal study that
recruited 243 preschool-aged children and their primary caregivers from
four low-income communities in Cape Town characterized by informal
housing, poverty, and exposure to violence
(\citeproc{ref-cook2024risk}{Cook et al., 2024}). For the current study,
the analytic sample comprised children with EF data available on any
measure at each timepoint: 217 children at T1 (M age = 4.70 years, SD =
0.60; 48.1\% female) and 189 at T2. For comprehensive details on study
sites, recruitment procedures, and sample characteristics, see Cook et
al. (\citeproc{ref-cook2024risk}{2024}).

\subsection{Measures}\label{measures}

\subsubsection{Executive Function}\label{executive-function}

EF was assessed using three measures from the Early Years Toolbox (EYT;
Howard and Melhuish (\citeproc{ref-howard2017early}{2017})), a suite of
iPad-based assessments with integrated audio instructions to ensure
standardized delivery, sequencing, and timing. The EYT has been
validated across diverse cultural contexts, including previous studies
in South Africa (\citeproc{ref-cook2019associations}{Cook et al., 2019};
\citeproc{ref-draper2020understanding}{Draper et al., 2020}) and other
countries (\citeproc{ref-hossain2021international}{Hossain et al.,
2021}; \citeproc{ref-munambah202124}{Munambah et al., 2021}).

\paragraph{Working Memory (Mr.~Ant).}\label{working-memory-mr.-ant}

This task requires children to remember the spatial locations of an
increasing number of colored stickers placed on a cartoon ant
(\citeproc{ref-howard2017early}{Howard \& Melhuish, 2017}). Each trial
proceeds as follows: Mr.~Ant appears with one or more stickers for 5
seconds; a blank screen is presented for 4 seconds; Mr.~Ant reappears
without stickers and children tap the locations where they believe the
stickers were. The task increases in difficulty from one to eight
stickers, with three trials at each level. Testing continues until
completion or failure on all three trials at the same level. Working
memory capacity was indexed by a point score calculated per Howard and
Melhuish (\citeproc{ref-howard2017early}{2017}): one point for each
consecutive level with at least two correct trials, plus 1/3 point for
each additional correct trial.

\paragraph{Inhibition (Go/No-Go).}\label{inhibition-gono-go}

This task measures children's ability to inhibit a prepotent response
(\citeproc{ref-howard2017early}{Howard \& Melhuish, 2017}). Children are
instructed to tap the screen for ``go'' trials (catch a fish; 80\% of
trials) and refrain from tapping for ``no-go'' trials (avoid sharks;
20\% of trials). The task comprises 75 trials divided into three blocks.
The preponderance of go trials generates a strong response tendency that
children must overcome on no-go trials. Inhibition was indexed by an
impulse control score representing the product of go and no-go
proportional accuracy, which accounts for both the strength of the
prepotent response and children's ability to inhibit it.

\paragraph{Cognitive Flexibility (Card
Sorting).}\label{cognitive-flexibility-card-sorting}

This task requires children to flexibly shift between sorting rules
(\citeproc{ref-howard2017early}{Howard \& Melhuish, 2017};
\citeproc{ref-zelazo2006dimensional}{Zelazo, 2006}). Children sort
stimuli (blue rabbits, red boats) first by one dimension (e.g., color),
then by the alternate dimension (e.g., shape). After completing
pre-switch and post-switch phases, children who meet performance
criteria proceed to a border phase requiring rule switching based on
whether stimuli are surrounded by a black border (sort by color) or not
(sort by shape). The cognitive flexibility task was originally scored as
switch accuracy (correct sorts on post-switch and border phases only;
range 0-12). However, this approach produced substantial floor effects
in the Australian sample, with 75 of 232 children (32.3\%) scoring zero
at T1. To address this, Australian scores were recalculated as total
accuracy across all phases, including the baseline pre-switch phase (6
points) plus post-switch and border phases (0-12 points), yielding a
range of 4-18. This scoring provided meaningful differentiation at the
lower end of the distribution, reducing floor performers to less than
1\%. South African scores retained the original switch-only scoring
(range 0-12), as floor effects were minimal in this sample (0\% at T1,
3.7\% at T2).

\subsubsection{Socioeconomic Status}\label{socioeconomic-status}

\subsubsection{Income}\label{income}

\paragraph{Australia.}\label{australia-1}

Caregivers reported gross annual household income using bands aligned
with Australia's Child Care Subsidy (CCS) eligibility thresholds: low
income (AUD \$0--\$45,144; eligible for 100\% CCS subsidy), middle
income (AUD \$45,145--\$156,914; eligible for subsidies on a sliding
scale), or high income (\textgreater AUD \$156,915; no subsidy
eligibility). These income bands reflect meaningful policy-defined
thresholds for accessing early childhood education support in Australia.

\paragraph{South Africa.}\label{south-africa-1}

Caregivers reported household income using items adapted from the
National Income Dynamics Survey (NIDS; http://www.nids.uct.ac.za), a
nationally representative panel study conducted in South Africa.
Participants indicated whether their household income was above, the
same as, or below specified income ranges, yielding seven ordered
categories. Due to small cell sizes in some categories and to facilitate
comparability with the Australian sample, income was collapsed into
three categories: low income (categories 1--2), middle income
(categories 3--5), and high income (categories 6--7). This tripartite
categorization captures meaningful gradations in household economic
resources while ensuring adequate sample sizes for analysis.

\subsubsection{The Home Learning
Envionment}\label{the-home-learning-envionment}

\paragraph{Australia.}\label{australia-2}

Caregivers reported the frequency of eight home learning and enrichment
activities in the past 7 days (e.g., reading to the child, visiting the
library, teaching sports or physical activities). This measure was
adapted from the Effective Pre-school, Primary and Secondary Education
(EPPSE) study (\citeproc{ref-melhuish2008effects}{Melhuish et al.,
2008}; \citeproc{ref-sylva2004effective}{Sylva et al., 2004}). Response
options for each activity were: 0 days, 1--2 days, 3--4 days, 5--6 days,
or 7 days. An HLE composite score was calculated by summing responses
across all eight activities.

\paragraph{South Africa.}\label{south-africa-2}

The home learning environment was assessed using the Home Learning
Environment questionnaire (\citeproc{ref-dawes2020early}{Dawes et al.,
2020}), which was developed for the South African context by combining
items from the UNICEF Multiple Indicator Cluster Survey
(https://mics.unicef.org) and the Home Learning Environment
questionnaire (\citeproc{ref-melhuish2010impact}{Melhuish, 2010}).
Caregivers reported how frequently (never, sometimes, or many times)
their child engaged in eight enrichment activities over the past 7 days
(e.g., reading books, counting things, singing songs). To align with the
Australian sample measures, we used the home learning activity (HLA)
frequency score, calculated as the sum of activity frequencies across
all eight activities, with higher scores indicating greater frequency of
enrichment activities.

\subsection{Statistical Analysis}\label{statistical-analysis}

\subsubsection{Network Estimation}\label{network-estimation}

We estimated EF network structure using Bayesian Gaussian Graphical
Models (BGGM) (\citeproc{ref-williams2020bayesian}{Williams \& Mulder,
2020a}, \citeproc{ref-williams2020bggm}{2020b}) implemented in the BGGM
R package (\citeproc{ref-BGGM}{Williams et al., 2025}). For each
cohort×wave combination, we fit a separate network model to capture the
conditional relationships between the three EF components (inhibition,
cognitive flexibility, and working memory) after controlling for age. We
used default priors and ran MCMC sampling for 5,050 iterations (5,000
posterior samples after 50 burn-in iterations).

\subsubsection{Edge Weights}\label{edge-weights}

Edges represent the conditional associations between pairs of EF
components. Technically, edge weights are partial correlations: the
correlation between two components after controlling for all other
components in the network and age. A positive edge indicates that two EF
components tend to covary (e.g., children with higher working memory
also tend to have higher inhibition, beyond what age would predict),
while a negative edge would indicate an inverse relationship. Edge
weights range from −1 to +1, with values closer to 0 indicating weaker
associations.

For each edge, we report the posterior median (a point estimate of the
edge strength) and the 95\% credible interval (CrI), which contains the
true edge weight with 95\% probability given the data and model. Unlike
frequentist confidence intervals, credible intervals can be directly
interpreted as probability statements about the parameter.

\subsubsection{Meaningfulness Threshold}\label{meaningfulness-threshold}

To distinguish meaningful edges from those that are small or negligible,
we adopted a Region of Practical Equivalence (ROPE) approach
(\citeproc{ref-kruschke2018rejecting}{Kruschke, 2018}). We defined the
ROPE as \textbar r\textbar{} ≤ 0.10, such that edge weights falling
within ±0.10 were considered practically equivalent to zero. For each
edge, we computed P(\textbar r\textbar{} \textgreater{} 0.10): the
posterior probability that the edge weight exceeds the ROPE threshold in
absolute value. Values close to 1 (e.g., P \textgreater{} 0.90) indicate
strong evidence that the edge is meaningfully different from zero, while
values close to 0.5 indicate substantial uncertainty.

This approach differs from traditional null hypothesis significance
testing in two ways. First, it focuses on practical significance (is the
effect large enough to matter?) rather than statistical significance (is
the effect different from exactly zero?). Second, it quantifies evidence
on a continuous scale rather than using a binary reject/fail-to-reject
decision rule.

\subsubsection{Global Strength}\label{global-strength}

Global strength summarizes overall network connectivity by summing the
absolute values of all unique edge weights. Higher global strength
indicates a more densely connected network where EF components are more
strongly coupled. We computed global strength for each posterior sample,
yielding a posterior distribution that captures uncertainty in this
summary metric.

Formally, for a network with \emph{p} nodes, global strength is: \[
GS = \sum_{i<j} |r_{ij}|
\]

where \emph{r\textsubscript{ij}} is the partial correlation between
nodes \emph{i} and \emph{j}. For our three-node networks, global
strength is simply \textbar r\textsubscript{inhib-cogflex}\textbar{} +
\textbar r\textsubscript{inhib-WM}\textbar{} +
\textbar r\textsubscript{cogflex-WM}\textbar.

\subsubsection{Centrality (Expected
Influence)}\label{centrality-expected-influence}

Expected Influence (\citeproc{ref-robinaugh2016identifying}{Robinaugh et
al., 2016}) quantifies the centrality of each node in the network---that
is, how strongly connected it is to other nodes. Expected influence is
computed as the sum of a node's edge weights to all other nodes (without
taking absolute values), preserving the sign of the relationships. Nodes
with higher expected influence are more central to the network and may
play a more important role in the overall system.

Formally, for node \emph{i}: \[
EI_i = \sum_{j \neq i} r_{ij}
\]

Unlike older centrality metrics (e.g., betweenness, closeness), expected
influence is appropriate for networks estimated from partial
correlations and does not require thresholding edges or converting the
network to a binary graph. We chose expected influence over strength
(which uses absolute values) because it preserves directional
information: a node can have high expected influence by being positively
connected to many nodes, whereas strength would treat positive and
negative edges equivalently. In EF networks where edges are
predominantly positive, the two metrics converge, but expected influence
provides a more nuanced picture if any negative edges emerge.

\subsubsection{Change and Comparison
Analyses}\label{change-and-comparison-analyses}

To test for developmental change within cohorts (RQ2), we computed
difference scores between adjacent waves (e.g., Δr = r\textsubscript{T2}
− r\textsubscript{T1}) by subtracting posterior samples pairwise. This
yields a posterior distribution of the change, from which we derived
95\% credible intervals and ROPE probabilities for the difference
(P(\textbar Δr\textbar{} \textgreater{} 0.10)).

For cross-cohort comparisons (RQ3), we computed cohort difference scores
(e.g., r\textsubscript{AU} − r\textsubscript{SA}) at matched waves. To
account for the bounded nature of correlations, we also report
differences on the Fisher z-scale (z = atanh(r)), which transforms
correlations to an unbounded scale where differences are more symmetric.
Results on both scales were substantively similar, indicating our
findings are not artifacts of scale constraints.

For difference-in-differences (DiD) contrasts, we tested whether cohorts
showed divergent developmental trajectories by computing
(Δr\textsubscript{T2-T1})\textsubscript{AU} −
(Δr\textsubscript{T2-T1})\textsubscript{SA}. A meaningful DiD would
indicate that one cohort changed more than the other over time.

\subsubsection{Moderation Analyses}\label{moderation-analyses}

To test whether socioeconomic factors moderate network structure (RQ4),
we adopted a stratified approach. Within each cohort, we split children
into High vs.~Low groups based on median splits of baseline (T1) income
and home learning environment (HLE), then fit separate BGGM models for
each group at each wave. We computed moderation effects as High − Low
edge differences, with ROPE probabilities indicating the strength of
evidence for moderation (P(\textbar High − Low\textbar{} \textgreater{}
0.10)). This stratified approach is more robust than including SES as a
continuous covariate in a single model, as it allows network structure
to differ nonlinearly across SES groups and does not assume constant
effects across the SES distribution.

\subsubsection{Measurement Invariance}\label{measurement-invariance}

We tested measurement invariance using multi-group confirmatory factor
analysis (CFA) in the lavaan R package
(\citeproc{ref-rosseel2012lavaan}{Rosseel, 2012}). To accommodate
heterogeneous measurement scales across cohorts (cognitive flexibility:
AU 4-18 including baseline sorting, SA 0-12 switch accuracy only;
working memory: 0-4.33 scaled score; inhibition: 0-1 proportion) and
differing performance distributions, we treated all three EF indicators
as ordinal variables, segmenting them into tertiles (Low/Medium/High)
based on pooled distributions. We fit a single-factor ordinal CFA model
across four groups simultaneously (AU\_T1, AU\_T2, SA\_T1, SA\_T2),
testing invariance across both cohorts and developmental timepoints
using robust weighted least squares estimation (WLSMV). We tested three
levels of invariance:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  \textbf{Configural invariance}: The same factor structure (three
  indicators loading on one factor) holds across all groups
\item
  \textbf{Metric invariance}: Factor loadings are equal across groups
  (components relate to the latent EF construct equivalently)
\item
  \textbf{Scalar invariance}: Thresholds (category boundaries for
  ordinal indicators) are equal across groups
\end{enumerate}

We evaluated invariance using chi-square difference tests (Δχ²) and
changes in fit indices (ΔCFI), with ΔCFI \textless{} 0.01 supporting
invariance (\citeproc{ref-cheung2002evaluating}{Cheung \& Rensvold,
2002}). Metric invariance is a prerequisite for comparing network
structures (relationships between EF components) across groups, while
scalar invariance is required for comparing mean levels.

\subsubsection{Software}\label{software}

All analyses were conducted in R (version 4.5.0). Network models were
fit using BGGM (version 2.1.5), measurement invariance tests used lavaan
(version 0.6.19), and visualizations used ggplot2 (version 4.0.0).
Analysis code is available at {[}include github url{]}.

\clearpage

\section{Results}\label{results}

\subsubsection{Measurement Invariance}\label{measurement-invariance-1}

To evaluate cross-cohort comparability of EF indicators, we conducted
multi-group confirmatory factor analyses (CFA) across four cohort×wave
groups (AU\_T1, AU\_T2, SA\_T1, SA\_T2), thereby testing invariance
simultaneously across countries and developmental timepoints. Because
cognitive flexibility exhibited pronounced floor effects in Australian
children at T1 (32.5\% scoring zero), all three EF indicators were
treated as ordinal variables using robust weighted least squares
estimation (WLSMV). Indicators were segmented into tertiles based on
pooled distributions to ensure adequate category representation.

In ordinal CFA, each observed categorical indicator reflects an
underlying continuous latent response variable partitioned by
thresholds. Factor loadings capture the strength of association between
the latent EF construct and each indicator, while thresholds capture
distributional placement of categories. This allows floor effect
severity to be represented through threshold parameters without
distorting factor loadings.

We estimated a one-factor model in a sequence of increasingly
constrained models. Configural invariance was supported. Constraining
factor loadings equal across groups (metric invariance) did not
significantly reduce fit (Δχ²(6) = 2.62, \emph{p} = 0.854; ΔCFI = 0),
indicating comparable strength of association between the EF factor and
its indicators. However, constraining thresholds (scalar invariance)
significantly worsened fit (Δχ²(6) = 35.29, \emph{p} \textless{} .001;
ΔCFI = -0.154), with CFI declining from 1 to 0.846, indicating
systematic threshold differences across groups. Metric invariance
supports comparison of network structures (relationships between EF
components) across cohorts, though absolute performance levels cannot be
compared (see Table~\ref{tbl-invariance}).

\begin{table}

{\caption{{Measurement Invariance Testing: Fit Indices and Model
Comparisons}{\label{tbl-invariance}}}
\vspace{-20pt}}

\begin{verbatim}
Error:
! object 'inv_table' not found
\end{verbatim}

\end{table}

\subsubsection{Descriptive Statistics and Preliminary
Analyses}\label{descriptive-statistics-and-preliminary-analyses}

Sample sizes for key variables are shown in
Table~\ref{tbl-render-table1} and Table~\ref{tbl-render-table2}.
Executive function scores increased with age across waves (see
Figure~\ref{fig-test-re-test-plot} and Figure~\ref{fig-age-ef-wave}),
with age-EF correlations ranging from r = 0.04 to 0.4. Zero-order
correlations between EF measures are shown in
Table~\ref{tbl-descriptives-zero-order}. Raw correlations ranged from r
= 0.13 to 0.36, with inhibition-working memory showing the strongest
association (mean r = 0.28). These moderate correlations motivated the
network approach: partial correlations reveal conditional dependencies
after controlling for shared variance and age-related trends.

\begin{table}

{\caption{{Zero-order correlations between EF measures by cohort and
wave}{\label{tbl-descriptives-zero-order}}}
\vspace{-20pt}}

\fontsize{8.0pt}{10.0pt}\selectfont
\begin{tabular*}{1\linewidth}{@{\extracolsep{\fill}}l|ccccc}
\toprule
Edge & AU T1 & AU T2 & AU T3 & SA T1 & SA T2 \\ 
\midrule\addlinespace[2.5pt]
Inhibition–Cognitive Flexibility & 0.13 & 0.22 & 0.24 & 0.24 & 0.13 \\ 
Inhibition–Working Memory & 0.30 & 0.36 & 0.34 & 0.19 & 0.20 \\ 
Cognitive Flexibility–Working Memory & 0.28 & 0.26 & 0.20 & 0.16 & 0.14 \\ 
\bottomrule
\end{tabular*}

\end{table}

\subsubsection{Research Question 1 (Primary): EF Network Structure
Within
Cohorts}\label{research-question-1-primary-ef-network-structure-within-cohorts}

Within each cohort and wave, what is the age-adjusted EF
network---defined by partial correlations among working memory,
inhibition, and cognitive flexibility---and what do global strength and
expected influence indicate about overall connectivity and node
centrality?

\subsubsection{Edges}\label{edges}

Within-wave age-adjusted partial correlations are summarized in
Table~\ref{tbl-rq1-gt-all} and visualized in
Figure~\ref{fig-rq1-edge-forest}. In Australia, edges involving working
memory showed the clearest evidence of coupling across waves. The
inhibition--working memory edge was consistently positive (T1: 0.27
{[}0.15, 0.39{]}; T2: 0.32 {[}0.20, 0.44{]}; T3: 0.30 {[}0.12, 0.47{]})
and reliably exceeded the meaningfulness threshold (T1:
P(\textbar r\textbar\textgreater0.1)=1.00; T2:
P(\textbar r\textbar\textgreater0.1)=1.00; T3:
P(\textbar r\textbar\textgreater0.1)=0.98). The cognitive
flexibility--working memory edge was also positive across waves (T1:
0.25 {[}0.13, 0.37{]}; T2: 0.20 {[}0.06, 0.33{]}; T3: 0.13 {[}-0.06,
0.32{]}) and exceeded the meaningfulness threshold (meaningfulness: T1:
P(\textbar r\textbar\textgreater0.1)=0.99; T2:
P(\textbar r\textbar\textgreater0.1)=0.92; T3:
P(\textbar r\textbar\textgreater0.1)=0.64). In contrast, the cognitive
flexibility--inhibition edge was weaker and more wave-dependent (T1:
0.06 {[}-0.07, 0.19{]}; T2: 0.15 {[}0.01, 0.28{]}; T3: 0.19 {[}-0.00,
0.37{]}), with less consistent evidence that it exceeded the
meaningfulness threshold (T1: P(\textbar r\textbar\textgreater0.1)=0.27;
T2: P(\textbar r\textbar\textgreater0.1)=0.75; T3:
P(\textbar r\textbar\textgreater0.1)=0.81).

In South Africa, the inhibition--working memory edge remained positive
across waves (T1: 0.17 {[}0.03, 0.30{]}; T2: 0.19 {[}0.04, 0.32{]}) and
met the meaningfulness criterion more consistently than the other edges
(T1: P(\textbar r\textbar\textgreater0.1)=0.83; T2:
P(\textbar r\textbar\textgreater0.1)=0.89). The cognitive
flexibility--inhibition edge was stronger at T1 (0.21 {[}0.08, 0.34{]})
but attenuated at T2 (0.10 {[}-0.05, 0.24{]}) and did not reliably
exceed the meaningfulness threshold at T2 (T1:
P(\textbar r\textbar\textgreater0.1)=0.95; T2:
P(\textbar r\textbar\textgreater0.1)=0.51). In contrast to the
Australian results, he cognitive flexibility--working memory edge was
comparatively weaker and uncertain across waves (T1: 0.12 {[}-0.01,
0.26{]}; T2: 0.12 {[}-0.03, 0.26{]}).

Figure~\ref{fig-rq1-network-graphs} visualizes the network structure.
The spatial layout is held constant across panels to facilitate
comparison. Working memory consistently occupied a well-connected
position, with edges to both inhibition and cognitive flexibility
appearing in all Australia networks and both South Africa networks. The
weaker cognitive flexibility--inhibition coupling in Australia at T1 is
evident in the absence of this edge
(P(\textbar r\textbar\textgreater0.10) = 0.50), while it appears at T2
and T3 when the relationship strengthens.

\clearpage

\begin{table}

{\caption{{Age-adjusted EF network summaries by cohort×wave. Panels show
edges, global strength, and expected influence (posterior median {[}95\%
CrI{]}). For edges, cells also show
\(P(|r| > r\text{ rope})\).}{\label{tbl-rq1-gt-all}}}
\vspace{-20pt}}

\fontsize{8.0pt}{10.0pt}\selectfont
\begin{tabular*}{1\linewidth}{@{\extracolsep{\fill}}l|cccccc}
\toprule
Measure & Cohort & Wave & N & \% missing cells & Median [95\% CrI] & P(|r|>0.1) \\ 
\midrule\addlinespace[2.5pt]
\multicolumn{7}{>{\raggedright\arraybackslash}m{1\linewidth}}{Edges} \\[2.5pt] 
\midrule\addlinespace[2.5pt]
ef\_cogflex - ef\_inhibition & AU & T1 & 232 & 0.1 & 0.06 [-0.07, 0.19] & 0.27 \\ 
ef\_cogflex - ef\_workingmem & AU & T1 & 232 & 0.1 & 0.25 [0.13, 0.37] & 0.99 \\ 
ef\_inhibition - ef\_workingmem & AU & T1 & 232 & 0.1 & 0.27 [0.15, 0.39] & 1.00 \\ 
ef\_cogflex - ef\_inhibition & AU & T2 & 217 & 0.8 & 0.15 [0.01, 0.28] & 0.75 \\ 
ef\_cogflex - ef\_workingmem & AU & T2 & 217 & 0.8 & 0.20 [0.06, 0.33] & 0.92 \\ 
ef\_inhibition - ef\_workingmem & AU & T2 & 217 & 0.8 & 0.32 [0.20, 0.44] & 1.00 \\ 
ef\_cogflex - ef\_inhibition & AU & T3 & 105 & 0.0 & 0.19 [-0.00, 0.37] & 0.81 \\ 
ef\_cogflex - ef\_workingmem & AU & T3 & 105 & 0.0 & 0.13 [-0.06, 0.32] & 0.64 \\ 
ef\_inhibition - ef\_workingmem & AU & T3 & 105 & 0.0 & 0.30 [0.12, 0.47] & 0.98 \\ 
ef\_cogflex - ef\_inhibition & SA & T1 & 217 & 2.0 & 0.21 [0.08, 0.34] & 0.95 \\ 
ef\_cogflex - ef\_workingmem & SA & T1 & 217 & 2.0 & 0.12 [-0.01, 0.26] & 0.64 \\ 
ef\_inhibition - ef\_workingmem & SA & T1 & 217 & 2.0 & 0.17 [0.03, 0.30] & 0.83 \\ 
ef\_cogflex - ef\_inhibition & SA & T2 & 189 & 1.2 & 0.10 [-0.05, 0.24] & 0.51 \\ 
ef\_cogflex - ef\_workingmem & SA & T2 & 189 & 1.2 & 0.12 [-0.03, 0.26] & 0.60 \\ 
ef\_inhibition - ef\_workingmem & SA & T2 & 189 & 1.2 & 0.19 [0.04, 0.32] & 0.89 \\ 
\midrule\addlinespace[2.5pt]
\multicolumn{7}{>{\raggedright\arraybackslash}m{1\linewidth}}{Global strength} \\[2.5pt] 
\midrule\addlinespace[2.5pt]
Global strength & AU & T1 & 232 & 0.1 & 0.59 [0.42, 0.75] &  \\ 
Global strength & AU & T2 & 217 & 0.8 & 0.66 [0.51, 0.81] &  \\ 
Global strength & AU & T3 & 105 & 0.0 & 0.64 [0.39, 0.84] &  \\ 
Global strength & SA & T1 & 217 & 2.0 & 0.51 [0.31, 0.68] &  \\ 
Global strength & SA & T2 & 189 & 1.2 & 0.42 [0.21, 0.61] &  \\ 
\midrule\addlinespace[2.5pt]
\multicolumn{7}{>{\raggedright\arraybackslash}m{1\linewidth}}{Expected influence} \\[2.5pt] 
\midrule\addlinespace[2.5pt]
Cognitive flexibility & AU & T1 & 232 & 0.1 & 0.31 [0.15, 0.46] &  \\ 
Inhibition & AU & T1 & 232 & 0.1 & 0.33 [0.18, 0.48] &  \\ 
Working memory & AU & T1 & 232 & 0.1 & 0.52 [0.36, 0.68] &  \\ 
Cognitive flexibility & AU & T2 & 217 & 0.8 & 0.34 [0.19, 0.50] &  \\ 
Inhibition & AU & T2 & 217 & 0.8 & 0.47 [0.31, 0.62] &  \\ 
Working memory & AU & T2 & 217 & 0.8 & 0.52 [0.36, 0.68] &  \\ 
Cognitive flexibility & AU & T3 & 105 & 0.0 & 0.32 [0.09, 0.54] &  \\ 
Inhibition & AU & T3 & 105 & 0.0 & 0.49 [0.25, 0.72] &  \\ 
Working memory & AU & T3 & 105 & 0.0 & 0.43 [0.20, 0.65] &  \\ 
Cognitive flexibility & SA & T1 & 217 & 2.0 & 0.34 [0.17, 0.51] &  \\ 
Inhibition & SA & T1 & 217 & 2.0 & 0.38 [0.20, 0.55] &  \\ 
Working memory & SA & T1 & 217 & 2.0 & 0.29 [0.12, 0.46] &  \\ 
Cognitive flexibility & SA & T2 & 189 & 1.2 & 0.22 [0.03, 0.40] &  \\ 
Inhibition & SA & T2 & 189 & 1.2 & 0.29 [0.10, 0.48] &  \\ 
Working memory & SA & T2 & 189 & 1.2 & 0.31 [0.10, 0.49] &  \\ 
\bottomrule
\end{tabular*}

\end{table}

\begin{figure}

\caption{\label{fig-rq1-edge-forest}\textbf{Within-wave EF coupling
(posterior partial correlations).} Points show posterior medians; bars
show 95\% credible intervals. Solid line = 0; dashed lines = ROPE
(±0.10).}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{EF_network_analysis_files/figure-pdf/fig-rq1-edge-forest-1.png}}

}

\end{figure}%

\begin{figure}

\caption{\label{fig-rq1-network-graphs}EF network structure by cohort
and wave. Nodes positioned consistently across panels; edge thickness
reflects partial correlation strength; edges with
P(\textbar r\textbar\textgreater0.10) \textless{} 0.75 are omitted for
clarity.}

\centering{

\includegraphics[width=1\linewidth,height=\textheight,keepaspectratio]{EF_network_analysis_files/figure-pdf/fig-rq1-network-graphs-1.png}

}

\end{figure}%

\clearpage

\subsubsection{Global strength}\label{global-strength-1}

Global strength estimates (sum of absolute partial correlations over
unique edges) are reported in Table~\ref{tbl-rq1-gt-all} and visualized
over time in Figure~\ref{fig-rq1-global-strength-trend}. Australia
showed stable global strength across waves (T1: 0.59 {[}0.42, 0.75{]};
T2: 0.66 {[}0.51, 0.81{]}; T3: 0.64 {[}0.39, 0.84{]}), whereas South
Africa showed lower global strength and attenuation from T1 to T2 (T1:
0.51 {[}0.31, 0.68{]}; T2: 0.42 {[}0.21, 0.61{]}).

\begin{figure}

\caption{\label{fig-rq1-global-strength-trend}Global strength over time
by cohort. Points show posterior median; whiskers show 95\% credible
intervals. Global strength is the sum of absolute partial correlations
over unique edges.}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{EF_network_analysis_files/figure-pdf/fig-rq1-global-strength-trend-1.png}}

}

\end{figure}%

\clearpage

\subsubsection{Centrality (Expected
influence)}\label{centrality-expected-influence-1}

Expected influence estimates (signed sum of incident partial
correlations) are summarized in Table~\ref{tbl-rq1-gt-all} and
visualized over time by node in Figure~\ref{fig-rq1-ei-trend-by-node-n}.
In Australia, expected influence was consistently positive across nodes
and waves, with working memory showing the highest expected influence
across waves (T1: 0.52 {[}0.36, 0.68{]}; T2: 0.52 {[}0.36, 0.68{]}; T3:
0.43 {[}0.20, 0.65{]}). Inhibition showed comparatively high expected
influence from T2 onward (T1: 0.33 {[}0.18, 0.48{]}; T2: 0.47 {[}0.31,
0.62{]}; T3: 0.49 {[}0.25, 0.72{]}), whereas cognitive flexibility was
lower and more stable across waves (T1: 0.31 {[}0.15, 0.46{]}; T2: 0.34
{[}0.19, 0.50{]}; T3: 0.32 {[}0.09, 0.54{]}). These patterns are evident
in Figure~\ref{fig-rq1-ei-trend-by-node-n}, which shows sustained
positive centrality for all three nodes in the Australian cohort, with
working memory and inhibition contributing most strongly to within-wave
coupling across time.

In South Africa, expected influence was positive but generally lower,
with attenuation from T1 to T2 for inhibition and cognitive flexibility
(inhibition: T1: 0.38 {[}0.20, 0.55{]}; T2: 0.29 {[}0.10, 0.48{]};
cognitive flexibility: T1: 0.34 {[}0.17, 0.51{]}; T2: 0.22 {[}0.03,
0.40{]}). Working memory showed comparatively stable expected influence
across waves (T1: 0.29 {[}0.12, 0.46{]}; T2: 0.31 {[}0.10, 0.49{]}).
Figure~\ref{fig-rq1-ei-trend-by-node-n} shows a downward shift from T1
to T2 for inhibition and cognitive flexibility in South Africa, while
working memory remains comparatively steady. \clearpage

\begin{figure}

\caption{\label{fig-rq1-ei-trend-by-node-n}Expected influence over time
by cohort and node. Points show posterior median; whiskers show 95\%
credible intervals. N per wave is shown beneath the zero line within
each panel.}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{EF_network_analysis_files/figure-pdf/fig-rq1-ei-trend-by-node-n-1.png}}

}

\end{figure}%

\clearpage

\subsubsection{Research Question 2 (Primary): Developmental Change
Within
Cohorts}\label{research-question-2-primary-developmental-change-within-cohorts}

Within each cohort, do the EF conditional associations (partial
correlations) change across adjacent waves (AU: T1→T2→T3; SA: T1→T2),
and if so, which specific edges strengthen or weaken over time?

Given metric invariance, we compared network structures across adjacent
waves within each cohort. For each wave transition, we computed
posterior distributions of change in edge weights (Δr = later wave −
earlier wave), global strength (Δ), and expected influence (Δ). We
evaluated whether changes exceeded a region of practical equivalence
(ROPE; \textbar Δr\textbar{} \textgreater{} 0.10) to distinguish
meaningful developmental change from negligible fluctuation.

We found little evidence for meaningful change in EF network summaries
across adjacent waves within either cohort (see
Table~\ref{tbl-rq2-gt-all}). Posterior 95\% CrIs for all Δs included 0,
and probabilities that edge changes exceeded the ROPE
(\textbar Δr\textbar{} \textgreater{} 0.10) were modest (≈0.3--0.6),
indicating substantial uncertainty and no clear support for meaningful
change.

\begin{table}

{\caption{{Change in EF network summaries across adjacent waves within
cohort. Cells show posterior median {[}95\% CrI{]} for Δ (later −
earlier). For edges, cells also show
\(P(|\Delta r| > 0.10)\).}{\label{tbl-rq2-gt-all}}}
\vspace{-20pt}}

\fontsize{8.0pt}{10.0pt}\selectfont
\begin{tabular*}{1\linewidth}{@{\extracolsep{\fill}}l|cccc}
\toprule
Measure & Cohort & Contrast & Median [95\% CrI] & P(|Δr|>0.1) \\ 
\midrule\addlinespace[2.5pt]
\multicolumn{5}{>{\raggedright\arraybackslash}m{1\linewidth}}{Edges (Δr)} \\[2.5pt] 
\midrule\addlinespace[2.5pt]
ef\_cogflex - ef\_inhibition & AU & T2 − T1 & 0.09 [-0.10, 0.27] & 0.48 \\ 
ef\_cogflex - ef\_workingmem & AU & T2 − T1 & -0.05 [-0.24, 0.13] & 0.35 \\ 
ef\_inhibition - ef\_workingmem & AU & T2 − T1 & 0.05 [-0.12, 0.22] & 0.32 \\ 
ef\_cogflex - ef\_inhibition & AU & T3 − T2 & 0.04 [-0.20, 0.27] & 0.43 \\ 
ef\_cogflex - ef\_workingmem & AU & T3 − T2 & -0.06 [-0.30, 0.17] & 0.47 \\ 
ef\_inhibition - ef\_workingmem & AU & T3 − T2 & -0.02 [-0.24, 0.19] & 0.35 \\ 
ef\_cogflex - ef\_inhibition & SA & T2 − T1 & -0.11 [-0.30, 0.08] & 0.56 \\ 
ef\_cogflex - ef\_workingmem & SA & T2 − T1 & -0.01 [-0.20, 0.19] & 0.32 \\ 
ef\_inhibition - ef\_workingmem & SA & T2 − T1 & 0.02 [-0.18, 0.22] & 0.32 \\ 
\midrule\addlinespace[2.5pt]
\multicolumn{5}{>{\raggedright\arraybackslash}m{1\linewidth}}{Global strength (Δ)} \\[2.5pt] 
\midrule\addlinespace[2.5pt]
Global strength & AU & T2 − T1 & 0.07 [-0.15, 0.30] &  \\ 
Global strength & AU & T3 − T2 & -0.03 [-0.31, 0.22] &  \\ 
Global strength & SA & T2 − T1 & -0.09 [-0.36, 0.18] &  \\ 
\midrule\addlinespace[2.5pt]
\multicolumn{5}{>{\raggedright\arraybackslash}m{1\linewidth}}{Expected influence (Δ)} \\[2.5pt] 
\midrule\addlinespace[2.5pt]
Cognitive flexibility & AU & T2 − T1 & 0.03 [-0.18, 0.26] & 0.39 \\ 
Inhibition & AU & T2 − T1 & 0.14 [-0.09, 0.36] & 0.66 \\ 
Working memory & AU & T2 − T1 & -0.01 [-0.24, 0.22] & 0.40 \\ 
Cognitive flexibility & AU & T3 − T2 & -0.02 [-0.29, 0.25] & 0.47 \\ 
Inhibition & AU & T3 − T2 & 0.02 [-0.25, 0.30] & 0.50 \\ 
Working memory & AU & T3 − T2 & -0.08 [-0.37, 0.19] & 0.55 \\ 
Cognitive flexibility & SA & T2 − T1 & -0.12 [-0.36, 0.13] & 0.59 \\ 
Inhibition & SA & T2 − T1 & -0.09 [-0.35, 0.17] & 0.54 \\ 
Working memory & SA & T2 − T1 & 0.02 [-0.24, 0.26] & 0.45 \\ 
\bottomrule
\end{tabular*}

\end{table}

\clearpage

\subsubsection{Research Question 3 (Secondary): Cross-Cohort
Comparisons}\label{research-question-3-secondary-cross-cohort-comparisons}

At matched waves (T1 and T2), do AU and SA differ in EF conditional
associations, and do the cohorts show divergent developmental
trajectories from T1 to T2 (difference-in-differences)?

A substantial floor effect was observed in Australian T1 cognitive
flexibility (32.5\% scoring zero), raising potential concerns for
cross-cohort network comparisons. Floor effects can induce artificial
correlations through range restriction and may bias partial correlation
estimates. To address this, we (1) Report cross-cohort comparisons using
the full sample (primary analysis), and (2) Conduct sensitivity analyses
excluding children who scored zero on cognitive flexibility at each
wave. If results converge across analyses, this would suggest floor
effects do not meaningfully distort cross-cohort comparisons. Divergence
would indicate that apparent cohort differences partly reflect
measurement artefacts.

\textbf{Main Analysis (Full Sample)}: At T1, posterior medians suggested
modest AU--SA differences in several edges; however, all 95\% credible
intervals overlapped zero. At T2, cohort differences were smaller and
predominantly positive, but again uncertain. In the
difference-in-differences analysis, most edges were centered near zero.
The largest deviation was observed for CogFlex--Inhibition (median =
0.2; 95\% CrI {[}-0.08, 0.47{]}; P(\textbar Δr\textbar\textgreater0.10)
= 0.78), though its credible interval still included zero, indicating
substantial uncertainty. Results were substantively unchanged when
differences were summarized on the Fisher z (atanh) scale
(Table~\ref{tbl-rq3-gt-edges-dual}).

\textbf{Sensitivity Analysis (Excluding Cognitive Flexibility Floor
Performers)}: Given the pronounced floor effect in Australian T1
cognitive flexibility (75/232 excluded {[}32.3\%{]}; AU T2: 42/217
{[}19.4\%{]}; SA T1: 0/217 {[}0\%{]}; SA T2: 7/189 {[}3.7\%{]}), we
refitted networks after wave-specific exclusion of children scoring zero
on cognitive flexibility. Estimates were highly similar in direction and
magnitude to the main analysis (see
Table~\ref{tbl-rq3-sensitivity-comparison}), with credible intervals
widening due to reduced sample size. Patterns at T2 and in the
difference-in-differences analysis were nearly identical.Together, these
results indicate that cross-cohort differences in EF network structure
are small and uncertain.

\begin{table}

{\caption{{Sensitivity analysis: Cross-cohort comparisons with vs
without floor performers. Main analysis includes all children;
sensitivity analysis uses wave-specific exclusion of children who scored
0 on any EF measure at that
wave.}{\label{tbl-rq3-sensitivity-comparison}}}
\vspace{-20pt}}

\fontsize{8.0pt}{10.0pt}\selectfont
\begin{tabular*}{1\linewidth}{@{\extracolsep{\fill}}l|cccc}
\toprule
 & \multicolumn{2}{c}{Main Analysis} & \multicolumn{2}{c}{Sensitivity (No Floor)\textsuperscript{\textit{1}}} \\ 
\cmidrule(lr){2-3} \cmidrule(lr){4-5}
Edge & Δr [95\% CrI] & P(|Δr|>0.10) & Δr [95\% CrI] & P(|Δr|>0.10) \\ 
\midrule\addlinespace[2.5pt]
\multicolumn{5}{>{\raggedright\arraybackslash}m{1\linewidth}}{Cohort difference (AU − SA) at T1} \\[2.5pt] 
\midrule\addlinespace[2.5pt]
ef\_cogflex - ef\_inhibition & -0.15 [-0.33, 0.03] & 0.72 & -0.02 [-0.22, 0.17] & 0.34 \\ 
ef\_cogflex - ef\_workingmem & 0.13 [-0.05, 0.30] & 0.61 & 0.13 [-0.07, 0.33] & 0.64 \\ 
ef\_inhibition - ef\_workingmem & 0.11 [-0.07, 0.28] & 0.55 & 0.08 [-0.12, 0.28] & 0.47 \\ 
\midrule\addlinespace[2.5pt]
\multicolumn{5}{>{\raggedright\arraybackslash}m{1\linewidth}}{Cohort difference (AU − SA) at T2} \\[2.5pt] 
\midrule\addlinespace[2.5pt]
ef\_cogflex - ef\_inhibition & 0.04 [-0.15, 0.24] & 0.37 & 0.18 [-0.02, 0.38] & 0.78 \\ 
ef\_cogflex - ef\_workingmem & 0.08 [-0.12, 0.27] & 0.45 & 0.02 [-0.19, 0.23] & 0.36 \\ 
ef\_inhibition - ef\_workingmem & 0.13 [-0.05, 0.31] & 0.65 & 0.10 [-0.10, 0.30] & 0.52 \\ 
\midrule\addlinespace[2.5pt]
\multicolumn{5}{>{\raggedright\arraybackslash}m{1\linewidth}}{Difference-in-differences (ΔAU − ΔSA)} \\[2.5pt] 
\midrule\addlinespace[2.5pt]
ef\_cogflex - ef\_inhibition & 0.20 [-0.08, 0.47] & 0.78 & 0.20 [-0.08, 0.49] & 0.78 \\ 
ef\_cogflex - ef\_workingmem & -0.05 [-0.31, 0.21] & 0.48 & -0.11 [-0.40, 0.18] & 0.60 \\ 
ef\_inhibition - ef\_workingmem & 0.03 [-0.24, 0.28] & 0.46 & 0.02 [-0.27, 0.29] & 0.50 \\ 
\bottomrule
\end{tabular*}
\begin{minipage}{\linewidth}
\vspace{.05em}
\textsuperscript{\textit{1}} Main analysis: all children. Sensitivity: wave-specific exclusion of children who scored 0 on Cognitive Flexibility at that wave (AU T1: 75/232 excluded [32.3\%]; AU T2: 42/217 excluded [19.4\%]; SA T1: 0/217 excluded [0.0\%]; SA T2: 7/189 excluded [3.7\%]).\\
\end{minipage}

\end{table}

\clearpage

\subsubsection{Research Question 4 (Exploratory): Socioeconomic
Moderation of Network
Structure}\label{research-question-4-exploratory-socioeconomic-moderation-of-network-structure}

Within each cohort, does EF network structure differ between children
from high versus low baseline (T1) household income and home learning
environments? Specifically, are edges systematically stronger or weaker
in high-SES groups across waves?

Within-cohort moderation analyses compared EF edge strengths across SES
strata within each cohort×wave. In AU at T2, the cognitive
flexibility--working memory edge differed between High and Middle income
groups (Δ = -0.47 {[}-0.80, -0.11{]};
P(\textbar Δ\textbar\textgreater0.10) = 0.98). In SA at T2, the
inhibition--working memory edge differed between High and Low income
groups (Δ = 0.40 {[}0.04, 0.75{]}; P(\textbar Δ\textbar\textgreater0.10)
= 0.95).

\begin{table}

{\caption{{Within-cohort moderation of EF edges by income and HLE. For
income, cells show posterior median {[}95\% CrI{]} for pairwise group
differences. For HLE, cells show High - Low differences. ROPE
probability indicates P(\textbar difference\textbar{} \textgreater{}
0.10).}{\label{tbl-rq4-moderation}}}
\vspace{-20pt}}

\fontsize{8.0pt}{10.0pt}\selectfont
\begin{tabular*}{1\linewidth}{@{\extracolsep{\fill}}l|ccccccc}
\toprule
Edge & Cohort & Wave & Contrast & n (A)\textsuperscript{\textit{1}} & n (B) & Median [95\% CrI] & P(|Δ|>0.1) \\ 
\midrule\addlinespace[2.5pt]
\multicolumn{8}{>{\raggedright\arraybackslash}m{1\linewidth}}{Income} \\[2.5pt] 
\midrule\addlinespace[2.5pt]
ef\_cogflex - ef\_inhibition & AU & T1 & High - Low & 43 & 20 & -0.19 [-0.71, 0.37] & 0.79 \\ 
ef\_cogflex - ef\_workingmem & AU & T1 & High - Low & 43 & 20 & -0.29 [-0.75, 0.25] & 0.84 \\ 
ef\_inhibition - ef\_workingmem & AU & T1 & High - Low & 43 & 20 & -0.16 [-0.66, 0.41] & 0.76 \\ 
ef\_cogflex - ef\_inhibition & AU & T1 & High - Middle & 43 & 126 & -0.14 [-0.51, 0.22] & 0.69 \\ 
ef\_cogflex - ef\_workingmem & AU & T1 & High - Middle & 43 & 126 & -0.15 [-0.51, 0.19] & 0.68 \\ 
ef\_inhibition - ef\_workingmem & AU & T1 & High - Middle & 43 & 126 & -0.24 [-0.60, 0.11] & 0.81 \\ 
ef\_cogflex - ef\_inhibition & AU & T1 & Middle - Low & 126 & 20 & -0.05 [-0.51, 0.44] & 0.70 \\ 
ef\_cogflex - ef\_workingmem & AU & T1 & Middle - Low & 126 & 20 & -0.14 [-0.50, 0.35] & 0.72 \\ 
ef\_inhibition - ef\_workingmem & AU & T1 & Middle - Low & 126 & 20 & 0.08 [-0.35, 0.58] & 0.70 \\ 
ef\_cogflex - ef\_inhibition & AU & T2 & High - Middle & 43 & 117 & 0.09 [-0.26, 0.44] & 0.64 \\ 
ef\_cogflex - ef\_workingmem & AU & T2 & High - Middle & 43 & 117 & -0.47 [-0.80, -0.11] & 0.98 \\ 
ef\_inhibition - ef\_workingmem & AU & T2 & High - Middle & 43 & 117 & -0.08 [-0.42, 0.22] & 0.59 \\ 
ef\_cogflex - ef\_inhibition & AU & T3 & High - Middle & 26 & 51 & -0.22 [-0.70, 0.24] & 0.79 \\ 
ef\_cogflex - ef\_workingmem & AU & T3 & High - Middle & 26 & 51 & 0.20 [-0.29, 0.63] & 0.77 \\ 
ef\_inhibition - ef\_workingmem & AU & T3 & High - Middle & 26 & 51 & -0.19 [-0.69, 0.28] & 0.76 \\ 
ef\_cogflex - ef\_inhibition & SA & T1 & High - Low & 52 & 78 & 0.25 [-0.11, 0.58] & 0.83 \\ 
ef\_cogflex - ef\_workingmem & SA & T1 & High - Low & 52 & 78 & 0.00 [-0.37, 0.36] & 0.59 \\ 
ef\_inhibition - ef\_workingmem & SA & T1 & High - Low & 52 & 78 & -0.29 [-0.66, 0.09] & 0.86 \\ 
ef\_cogflex - ef\_inhibition & SA & T1 & High - Middle & 52 & 80 & 0.11 [-0.23, 0.42] & 0.63 \\ 
ef\_cogflex - ef\_workingmem & SA & T1 & High - Middle & 52 & 80 & 0.16 [-0.22, 0.51] & 0.71 \\ 
ef\_inhibition - ef\_workingmem & SA & T1 & High - Middle & 52 & 80 & -0.20 [-0.57, 0.20] & 0.76 \\ 
ef\_cogflex - ef\_inhibition & SA & T1 & Middle - Low & 80 & 78 & 0.14 [-0.16, 0.45] & 0.66 \\ 
ef\_cogflex - ef\_workingmem & SA & T1 & Middle - Low & 80 & 78 & -0.15 [-0.46, 0.17] & 0.69 \\ 
ef\_inhibition - ef\_workingmem & SA & T1 & Middle - Low & 80 & 78 & -0.09 [-0.40, 0.21] & 0.58 \\ 
ef\_cogflex - ef\_inhibition & SA & T2 & High - Low & 47 & 59 & 0.03 [-0.36, 0.42] & 0.63 \\ 
ef\_cogflex - ef\_workingmem & SA & T2 & High - Low & 47 & 59 & -0.30 [-0.68, 0.08] & 0.87 \\ 
ef\_inhibition - ef\_workingmem & SA & T2 & High - Low & 47 & 59 & 0.40 [0.04, 0.75] & 0.95 \\ 
ef\_cogflex - ef\_inhibition & SA & T2 & High - Middle & 47 & 63 & 0.16 [-0.24, 0.55] & 0.72 \\ 
ef\_cogflex - ef\_workingmem & SA & T2 & High - Middle & 47 & 63 & -0.13 [-0.52, 0.25] & 0.69 \\ 
ef\_inhibition - ef\_workingmem & SA & T2 & High - Middle & 47 & 63 & 0.24 [-0.12, 0.58] & 0.81 \\ 
ef\_cogflex - ef\_inhibition & SA & T2 & Middle - Low & 63 & 59 & -0.14 [-0.50, 0.24] & 0.68 \\ 
ef\_cogflex - ef\_workingmem & SA & T2 & Middle - Low & 63 & 59 & -0.17 [-0.52, 0.18] & 0.71 \\ 
ef\_inhibition - ef\_workingmem & SA & T2 & Middle - Low & 63 & 59 & 0.16 [-0.20, 0.52] & 0.71 \\ 
\midrule\addlinespace[2.5pt]
\multicolumn{8}{>{\raggedright\arraybackslash}m{1\linewidth}}{HLE} \\[2.5pt] 
\midrule\addlinespace[2.5pt]
ef\_cogflex - ef\_inhibition & AU & T1 & High - Low & 86 & 103 & 0.12 [-0.17, 0.41] & 0.63 \\ 
ef\_cogflex - ef\_workingmem & AU & T1 & High - Low & 86 & 103 & -0.01 [-0.29, 0.26] & 0.46 \\ 
ef\_inhibition - ef\_workingmem & AU & T1 & High - Low & 86 & 103 & -0.06 [-0.33, 0.22] & 0.51 \\ 
ef\_cogflex - ef\_inhibition & AU & T2 & High - Low & 91 & 88 & 0.18 [-0.12, 0.46] & 0.73 \\ 
ef\_cogflex - ef\_workingmem & AU & T2 & High - Low & 91 & 88 & 0.17 [-0.11, 0.45] & 0.70 \\ 
ef\_inhibition - ef\_workingmem & AU & T2 & High - Low & 91 & 88 & 0.04 [-0.23, 0.32] & 0.48 \\ 
ef\_cogflex - ef\_inhibition & AU & T3 & High - Low & 42 & 43 & 0.28 [-0.15, 0.68] & 0.83 \\ 
ef\_cogflex - ef\_workingmem & AU & T3 & High - Low & 42 & 43 & 0.25 [-0.17, 0.67] & 0.81 \\ 
ef\_inhibition - ef\_workingmem & AU & T3 & High - Low & 42 & 43 & -0.04 [-0.45, 0.37] & 0.64 \\ 
ef\_cogflex - ef\_inhibition & SA & T1 & High - Low & 103 & 107 & -0.05 [-0.32, 0.21] & 0.49 \\ 
ef\_cogflex - ef\_workingmem & SA & T1 & High - Low & 103 & 107 & 0.16 [-0.11, 0.44] & 0.71 \\ 
ef\_inhibition - ef\_workingmem & SA & T1 & High - Low & 103 & 107 & 0.04 [-0.24, 0.31] & 0.49 \\ 
ef\_cogflex - ef\_inhibition & SA & T2 & High - Low & 85 & 84 & -0.12 [-0.42, 0.18] & 0.63 \\ 
ef\_cogflex - ef\_workingmem & SA & T2 & High - Low & 85 & 84 & 0.01 [-0.28, 0.31] & 0.52 \\ 
ef\_inhibition - ef\_workingmem & SA & T2 & High - Low & 85 & 84 & 0.14 [-0.17, 0.44] & 0.67 \\ 
\bottomrule
\end{tabular*}
\begin{minipage}{\linewidth}
\vspace{.05em}
\textsuperscript{\textit{1}} For income contrasts: A and B refer to the two groups being compared (e.g., High-Low: A=High, B=Low). Due to attrition, AU T2 Low (n=19) and T3 Low (n=8) groups fell below the n=20 threshold; only High-Middle and High-Low contrasts are available for these waves.\\
\end{minipage}

\end{table}

\clearpage

\section{Discussion}\label{discussion}

\clearpage

\section{References}\label{references}

\phantomsection\label{refs}
\begin{CSLReferences}{1}{0}
\bibitem[\citeproctext]{ref-baum2020development}
Baum, G. L., Cui, Z., Roalf, D. R., Ciric, R., Betzel, R. F., Larsen,
B., Cieslak, M., Cook, P. A., Xia, C. H., Moore, T. M., et al. (2020).
Development of structure--function coupling in human brain networks
during youth. \emph{Proceedings of the National Academy of Sciences},
\emph{117}(1), 771--778.

\bibitem[\citeproctext]{ref-best2010developmental}
Best, J. R., \& Miller, P. H. (2010). A developmental perspective on
executive function. \emph{Child Development}, \emph{81}(6), 1641--1660.

\bibitem[\citeproctext]{ref-blair2016executive}
Blair, C. (2016). Executive function and early childhood education.
\emph{Current Opinion in Behavioral Sciences}, \emph{10}, 102--107.

\bibitem[\citeproctext]{ref-brydges2012unitary}
Brydges, C. R., Reid, C. L., Fox, A. M., \& Anderson, M. (2012). A
unitary executive function predicts intelligence in children.
\emph{Intelligence}, \emph{40}(5), 458--469.

\bibitem[\citeproctext]{ref-buss2018changes}
Buss, A. T., \& Spencer, J. P. (2018). Changes in frontal and posterior
cortical activity underlie the early emergence of executive function.
\emph{Developmental Science}, \emph{21}(4), e12602.

\bibitem[\citeproctext]{ref-cheung2002evaluating}
Cheung, G. W., \& Rensvold, R. B. (2002). Evaluating goodness-of-fit
indexes for testing measurement invariance. \emph{Structural Equation
Modeling}, \emph{9}(2), 233--255.

\bibitem[\citeproctext]{ref-collette2006exploration}
Collette, F., Hogge, M., Salmon, E., \& Van der Linden, M. (2006).
Exploration of the neural substrates of executive functioning by
functional neuroimaging. \emph{Neuroscience}, \emph{139}(1), 209--221.

\bibitem[\citeproctext]{ref-cook2024risk}
Cook, C. J., Howard, S. J., Makaula, H., Merkley, R., Mshudulu, M.,
Tshetu, N., Scerif, G., \& Draper, C. E. (2024). Risk and protective
factors for executive function in vulnerable south african preschool-age
children. \emph{Journal of Cognition}, \emph{7}(1), 58.

\bibitem[\citeproctext]{ref-cook2019associations}
Cook, C. J., Howard, S. J., Scerif, G., Twine, R., Kahn, K., Norris, S.
A., \& Draper, C. E. (2019). Associations of physical activity and gross
motor skills with executive function in preschool children from
low-income south african settings. \emph{Developmental Science},
\emph{22}(5), e12820.

\bibitem[\citeproctext]{ref-crone2006neurocognitive}
Crone, E. A., Wendelken, C., Donohue, S., Leijenhorst, L. van, \& Bunge,
S. A. (2006). Neurocognitive development of the ability to manipulate
information in working memory. \emph{Proceedings of the National Academy
of Sciences}, \emph{103}(24), 9315--9320.

\bibitem[\citeproctext]{ref-cui2020optimization}
Cui, Z., Stiso, J., Baum, G. L., Kim, J. Z., Roalf, D. R., Betzel, R.
F., Gu, S., Lu, Z., Xia, C. H., He, X., et al. (2020). Optimization of
energy state transition trajectory supports the development of executive
function during youth. \emph{Elife}, \emph{9}, e53060.

\bibitem[\citeproctext]{ref-dawes2020early}
Dawes, A., Biersteker, L., Girdwood, L., Snelling, M., \& Horler, J.
(2020). The early learning programme outcomes study technical report.
\emph{Claremont Cape Town: Innovation Edge (Www. Innovationedge. Org.
Za) and Ilifa Labantwana (Www. Ilifalabantwana. Co. Za)}.

\bibitem[\citeproctext]{ref-diamond2013executive}
Diamond, A. (2013). Executive functions. \emph{Annual Review of
Psychology}, \emph{64}(1), 135--168.

\bibitem[\citeproctext]{ref-dosenbach2008dual}
Dosenbach, N. U., Fair, D. A., Cohen, A. L., Schlaggar, B. L., \&
Petersen, S. E. (2008). A dual-networks architecture of top-down
control. \emph{Trends in Cognitive Sciences}, \emph{12}(3), 99--105.

\bibitem[\citeproctext]{ref-draper2020understanding}
Draper, C., Tomaz, S. A., Cook, C. J., Jugdav, S. S., Ramsammy, C.,
Heerden, A. van, Vilakazi, K., Cockcroft, K., Howard, S., Okely, A., et
al. (2020). Understanding the influence of 24-hour movement behaviours
on the health and development of preschool children from low-income
south african settings: The SUNRISE pilot study. \emph{South African
Journal of Sports Medicine}, \emph{32}(1), 1--7.

\bibitem[\citeproctext]{ref-engelhardt2019neural}
Engelhardt, L. E., Harden, K. P., Tucker-Drob, E. M., \& Church, J. A.
(2019). The neural architecture of executive functions is established by
middle childhood. \emph{NeuroImage}, \emph{185}, 479--489.

\bibitem[\citeproctext]{ref-ezekiel2013dimensional}
Ezekiel, F., Bosma, R., \& Morton, J. B. (2013). Dimensional change card
sort performance associated with age-related differences in functional
connectivity of lateral prefrontal cortex. \emph{Developmental Cognitive
Neuroscience}, \emph{5}, 40--50.

\bibitem[\citeproctext]{ref-fiske2019neural}
Fiske, A., \& Holmboe, K. (2019). Neural substrates of early executive
function development. \emph{Developmental Review}, \emph{52}, 42--62.

\bibitem[\citeproctext]{ref-friedman2017unity}
Friedman, N. P., \& Miyake, A. (2017). Unity and diversity of executive
functions: Individual differences as a window on cognitive structure.
\emph{Cortex}, \emph{86}, 186--204.

\bibitem[\citeproctext]{ref-friedman2008individual}
Friedman, N. P., Miyake, A., Young, S. E., DeFries, J. C., Corley, R.
P., \& Hewitt, J. K. (2008). Individual differences in executive
functions are almost entirely genetic in origin. \emph{Journal of
Experimental Psychology: General}, \emph{137}(2), 201.

\bibitem[\citeproctext]{ref-garon2008executive}
Garon, N., Bryson, S. E., \& Smith, I. M. (2008). Executive function in
preschoolers: A review using an integrative framework.
\emph{Psychological Bulletin}, \emph{134}(1), 31.

\bibitem[\citeproctext]{ref-hossain2021international}
Hossain, M. S., Deeba, I. M., Hasan, M., Kariippanon, K. E., Chong, K.
H., Cross, P. L., Ferdous, S., \& Okely, A. D. (2021). International
study of 24-h movement behaviors of early years (SUNRISE): A pilot study
from bangladesh. \emph{Pilot and Feasibility Studies}, \emph{7}(1), 176.

\bibitem[\citeproctext]{ref-howard2017early}
Howard, S. J., \& Melhuish, E. (2017). An early years toolbox for
assessing early executive function, language, self-regulation, and
social development: Validity, reliability, and preliminary norms.
\emph{Journal of Psychoeducational Assessment}, \emph{35}(3), 255--275.

\bibitem[\citeproctext]{ref-johnson2011interactive}
Johnson, M. H. (2011). Interactive specialization: A domain-general
framework for human functional brain development? \emph{Developmental
Cognitive Neuroscience}, \emph{1}(1), 7--21.

\bibitem[\citeproctext]{ref-karr2018unity}
Karr, J. E., Areshenkoff, C. N., Rast, P., Hofer, S. M., Iverson, G. L.,
\& Garcia-Barrera, M. A. (2018). The unity and diversity of executive
functions: A systematic review and re-analysis of latent variable
studies. \emph{Psychological Bulletin}, \emph{144}(11), 1147.

\bibitem[\citeproctext]{ref-kelsey2025forming}
Kelsey, C., Kamenetskiy, A., Mulligan, K., Tiras, C., Kent, M., Bayet,
L., Richards, J., Bosquet Enlow, M., \& Nelson, C. A. (2025). Forming
connections: Functional brain connectivity is associated with executive
functioning abilities in early childhood. \emph{Developmental Science},
\emph{28}(2), e13604.

\bibitem[\citeproctext]{ref-kruschke2018rejecting}
Kruschke, J. (2018). \emph{Rejecting or accepting parameter values in
bayesian estimation. Advances in methods and practices in psychological
science, 1 (2), 270--280}.

\bibitem[\citeproctext]{ref-lee2013developmental}
Lee, K., Bull, R., \& Ho, R. M. (2013). Developmental changes in
executive functioning. \emph{Child Development}, \emph{84}(6),
1933--1953.

\bibitem[\citeproctext]{ref-lehto2003dimensions}
Lehto, J. E., Juujärvi, P., Kooistra, L., \& Pulkkinen, L. (2003).
Dimensions of executive functioning: Evidence from children.
\emph{British Journal of Developmental Psychology}, \emph{21}(1),
59--80.

\bibitem[\citeproctext]{ref-li2025structural}
Li, Y., Ganesan, K., Smid, C. R., Thompson, A., Canigueral, R., Royer,
J., Bernhardt, B., \& Steinbeis, N. (2025). Structural brain basis of
latent factors of executive functions in childhood. \emph{Developmental
Cognitive Neuroscience}, \emph{71}, 101504.

\bibitem[\citeproctext]{ref-mckenna2017informing}
McKenna, R., Rushe, T., \& Woodcock, K. A. (2017). Informing the
structure of executive function in children: A meta-analysis of
functional neuroimaging data. \emph{Frontiers in Human Neuroscience},
\emph{11}, 154.

\bibitem[\citeproctext]{ref-melhuish2010impact}
Melhuish, E. C. (2010). \emph{Impact of the home learning environment on
child cognitive development: Secondary analysis of data from" growing up
in scotland"}.

\bibitem[\citeproctext]{ref-melhuish2008effects}
Melhuish, E. C., Phan, M. B., Sylva, K., Sammons, P., Siraj-Blatchford,
I., \& Taggart, B. (2008). Effects of the home learning environment and
preschool center experience upon literacy and numeracy development in
early primary school. \emph{Journal of Social Issues}, \emph{64}(1),
95--114.

\bibitem[\citeproctext]{ref-menu2024latent}
Menu, I., Borst, G., \& Cachia, A. (2024). Latent network analysis of
executive functions across development. \emph{Journal of Cognition},
\emph{7}(1), 31.

\bibitem[\citeproctext]{ref-miller2012latent}
Miller, M. R., Giesbrecht, G. F., Müller, U., McInerney, R. J., \&
Kerns, K. A. (2012). A latent variable approach to determining the
structure of executive function in preschool children. \emph{Journal of
Cognition and Development}, \emph{13}(3), 395--423.

\bibitem[\citeproctext]{ref-miyake2000unity}
Miyake, A., Friedman, N. P., Emerson, M. J., Witzki, A. H., Howerter,
A., \& Wager, T. D. (2000). The unity and diversity of executive
functions and their contributions to complex {``frontal lobe''} tasks: A
latent variable analysis. \emph{Cognitive Psychology}, \emph{41}(1),
49--100.

\bibitem[\citeproctext]{ref-munambah202124}
Munambah, N., Gretschel, P., Muchirahondo, F., Chiwaridzo, M.,
Chikwanha, T., Kariippanon, K. E., Chong, K. H., Cross, P. L., Draper,
C. E., \& Okely, A. D. (2021). 24 hour movement behaviours and the
health and development of pre-school children from zimbabwean settings:
The SUNRISE pilot study. \emph{South African Journal of Sports
Medicine}, \emph{33}(1), v33i1a10864.

\bibitem[\citeproctext]{ref-nelson2016structure}
Nelson, J. M., James, T. D., Chevalier, N., Clark, C. A., \& Espy, K. A.
(2016). \emph{Structure, measurement, and development of preschool
executive function.}

\bibitem[\citeproctext]{ref-niendam2012meta}
Niendam, T. A., Laird, A. R., Ray, K. L., Dean, Y. M., Glahn, D. C., \&
Carter, C. S. (2012). Meta-analytic evidence for a superordinate
cognitive control network subserving diverse executive functions.
\emph{Cognitive, Affective, \& Behavioral Neuroscience}, \emph{12}(2),
241--268.

\bibitem[\citeproctext]{ref-o2008neurodevelopmental}
O'Hare, E. D., Lu, L. H., Houston, S. M., Bookheimer, S. Y., \& Sowell,
E. R. (2008). Neurodevelopmental changes in verbal working memory
load-dependency: An fMRI investigation. \emph{Neuroimage}, \emph{42}(4),
1678--1685.

\bibitem[\citeproctext]{ref-reilly2022developmental}
Reilly, S. E., Downer, J. T., \& Grimm, K. J. (2022). Developmental
trajectories of executive functions from preschool to kindergarten.
\emph{Developmental Science}, \emph{25}(5), e13236.

\bibitem[\citeproctext]{ref-robinaugh2016identifying}
Robinaugh, D. J., Millner, A. J., \& McNally, R. J. (2016). Identifying
highly influential nodes in the complicated grief network. \emph{Journal
of Abnormal Psychology}, \emph{125}(6), 747.

\bibitem[\citeproctext]{ref-rodriguez2022inhibition}
Rodrı́guez-Nieto, G., Seer, C., Sidlauskaite, J., Vleugels, L., Van Roy,
A., Hardwick, R., \& Swinnen, S. (2022). Inhibition, shifting and
updating: Inter and intra-domain commonalities and differences from an
executive functions activation likelihood estimation meta-analysis.
\emph{NeuroImage}, \emph{264}, 119665.

\bibitem[\citeproctext]{ref-rosseel2012lavaan}
Rosseel, Y. (2012). Lavaan: An r package for structural equation
modeling. \emph{Journal of Statistical Software}, \emph{48}(1), 1--36.

\bibitem[\citeproctext]{ref-rottschy2012modelling}
Rottschy, C., Langner, R., Dogan, I., Reetz, K., Laird, A. R., Schulz,
J. B., Fox, P. T., \& Eickhoff, S. B. (2012). Modelling neural
correlates of working memory: A coordinate-based meta-analysis.
\emph{Neuroimage}, \emph{60}(1), 830--846.

\bibitem[\citeproctext]{ref-rubia2013functional}
Rubia, K. (2013). Functional brain imaging across development.
\emph{European Child \& Adolescent Psychiatry}, \emph{22}(12), 719--731.

\bibitem[\citeproctext]{ref-shanmugan2016neural}
Shanmugan, S., \& Satterthwaite, T. D. (2016). Neural markers of the
development of executive function: Relevance for education.
\emph{Current Opinion in Behavioral Sciences}, \emph{10}, 7--13.

\bibitem[\citeproctext]{ref-sylva2004effective}
Sylva, K., Melhuish, E., Sammons, P., Siraj-Blatchford, I., \& Taggart,
B. (2004). \emph{The effective provision of pre-school education (EPPE)
project: Final report: A longitudinal study funded by the DfES
1997-2004}. Institute of Education, University of London/Department for
Education and~\ldots.

\bibitem[\citeproctext]{ref-tamnes2017development}
Tamnes, C. K., Herting, M. M., Goddings, A.-L., Meuwese, R., Blakemore,
S.-J., Dahl, R. E., Güroğlu, B., Raznahan, A., Sowell, E. R., Crone, E.
A., et al. (2017). Development of the cerebral cortex across
adolescence: A multisample study of inter-related longitudinal changes
in cortical volume, surface area, and thickness. \emph{Journal of
Neuroscience}, \emph{37}(12), 3402--3412.

\bibitem[\citeproctext]{ref-usai2014latent}
Usai, M. C., Viterbori, P., Traverso, L., \& De Franchis, V. (2014).
Latent structure of executive function in five-and six-year-old
children: A longitudinal study. \emph{European Journal of Developmental
Psychology}, \emph{11}(4), 447--462.

\bibitem[\citeproctext]{ref-vandierendonck2021utility}
Vandierendonck, A. (2021). On the utility of integrated speed-accuracy
measures when speed-accuracy trade-off is present. \emph{Journal of
Cognition}, \emph{4}(1), 22.

\bibitem[\citeproctext]{ref-wiebe2008using}
Wiebe, S. A., Espy, K. A., \& Charak, D. (2008). Using confirmatory
factor analysis to understand executive control in preschool children:
I. Latent structure. \emph{Developmental Psychology}, \emph{44}(2), 575.

\bibitem[\citeproctext]{ref-williams2020bayesian}
Williams, D. R., \& Mulder, J. (2020a). Bayesian hypothesis testing for
gaussian graphical models: Conditional independence and order
constraints. \emph{Journal of Mathematical Psychology}, \emph{99},
102441.

\bibitem[\citeproctext]{ref-williams2020bggm}
Williams, D. R., \& Mulder, J. (2020b). BGGM: Bayesian gaussian
graphical models in r. \emph{The Journal of Open Source Software},
\emph{5}(51), 2111.

\bibitem[\citeproctext]{ref-BGGM}
Williams, D. R., Mulder, J., \& Rast, P. (2025). \emph{BGGM: Bayesian
gaussian graphical models} (R package version 2.1.6). The Comprehensive
R Archive Network (CRAN).
\url{https://doi.org/10.32614/CRAN.package.BGGM}

\bibitem[\citeproctext]{ref-willoughby2012measurement}
Willoughby, M. T., Blair, C. B., Wirth, R., \& Greenberg, M. (2012). The
measurement of executive function at age 5: Psychometric properties and
relationship to academic achievement. \emph{Psychological Assessment},
\emph{24}(1), 226.

\bibitem[\citeproctext]{ref-zelazo2006dimensional}
Zelazo, P. D. (2006). The dimensional change card sort (DCCS): A method
of assessing executive function in children. \emph{Nature Protocols},
\emph{1}(1), 297--301.

\bibitem[\citeproctext]{ref-zelazo2016executive}
Zelazo, P. D., Blair, C. B., \& Willoughby, M. T. (2016). Executive
function: Implications for education. NCER 2017-2000. \emph{National
Center for Education Research}.

\bibitem[\citeproctext]{ref-zhang2017large}
Zhang, R., Geng, X., \& Lee, T. M. (2017). Large-scale functional neural
network correlates of response inhibition: An fMRI meta-analysis.
\emph{Brain Structure and Function}, \emph{222}(9), 3973--3990.

\end{CSLReferences}

\appendix

\section{Demographics}\label{apx-render-table1}

\begin{landscape}

\begin{table}

{\caption{{Age and executive function by country and timepoint. All
summaries are anchored to children with any EF observed at that
timepoint (partial EF allowed).}{\label{tbl-render-table1}}}
\vspace{-20pt}}

\fontsize{8.0pt}{10.0pt}\selectfont
\begin{tabular*}{1\linewidth}{@{\extracolsep{\fill}}l|l|ccccc}
\toprule
\multicolumn{2}{c}{} & Australia — T1 & Australia — T2 & Australia — T3 & SA — T1 & SA — T2 \\ 
\midrule\addlinespace[2.5pt]
{\bfseries \multirow[t]{6}{*}{Executive function}} & Cognitive flexibility, Mean (SD) & 4.69 (4.12) & 5.99 (4.01) & 8.85 (1.97) & 7.73 (2.15) & 8.16 (2.73) \\ 
 & Cognitive flexibility, n & 231 & 216 & 105 & 214 & 187 \\ 
 & Inhibition, Mean (SD) & 0.56 (0.19) & 0.70 (0.19) & 0.77 (0.17) & 0.59 (0.24) & 0.73 (0.21) \\ 
 & Inhibition, n & 232 & 215 & 105 & 213 & 188 \\ 
 & Working memory, Mean (SD) & 1.50 (0.95) & 1.82 (0.89) & 2.56 (0.79) & 1.55 (0.81) & 2.00 (0.83) \\ 
 & Working memory, n & 232 & 215 & 105 & 211 & 188 \\ 
\midrule\addlinespace[2.5pt]
{\bfseries \multirow[t]{2}{*}{Age}} & Age (years), Mean (SD) & 4.43 (0.38) & 4.99 (0.38) & 5.92 (0.33) & 4.70 (0.60) & 5.35 (0.57) \\ 
 & Age (years), Median [min, max] & 4.44 [3.20, 5.24] & 4.99 [3.74, 5.88] & 5.90 [5.27, 6.59] & 4.68 [2.80, 5.89] & 5.37 [3.54, 6.55] \\ 
\midrule\addlinespace[2.5pt]
{\bfseries \multirow[t]{3}{*}{Sex}} & Female, n (\%) & 107 (46.1\%) & 101 (46.5\%) & 53 (50.5\%) & 117 (48.1\%) & 87 (35.8\%) \\ 
 & Male, n (\%) & 125 (53.9\%) & 116 (53.5\%) & 52 (49.5\%) & 126 (51.9\%) & 105 (43.2\%) \\ 
 & Missing, n (\%) & — & — & — & — & 51 (21.0\%) \\ 
\bottomrule
\end{tabular*}

\end{table}

\end{landscape}

\begin{landscape}

\begin{table}

{\caption{{Socioeconomic status and home learning environment by country
and timepoint.}{\label{tbl-render-table2}}}
\vspace{-20pt}}

\fontsize{8.0pt}{10.0pt}\selectfont
\begin{tabular*}{1\linewidth}{@{\extracolsep{\fill}}l|l|ccccc}
\toprule
\multicolumn{2}{c}{} & Australia — T1 & Australia — T2 & Australia — T3 & SA — T1 & SA — T2 \\ 
\midrule\addlinespace[2.5pt]
{\bfseries \multirow[t]{6}{*}{Caregiver education (AUS)}} & 1 & 18 (7.8\%) & 17 (7.8\%) & 8 (7.6\%) & — & — \\ 
 & 2 & 16 (6.9\%) & 15 (6.9\%) & 6 (5.7\%) & — & — \\ 
 & 3 & 61 (26.3\%) & 56 (25.8\%) & 24 (22.9\%) & — & — \\ 
 & 4 & 68 (29.3\%) & 65 (30.0\%) & 33 (31.4\%) & — & — \\ 
 & 5 & 35 (15.1\%) & 34 (15.7\%) & 16 (15.2\%) & — & — \\ 
 & — & 34 (14.7\%) & 30 (13.8\%) & 18 (17.1\%) & — & — \\ 
\midrule\addlinespace[2.5pt]
{\bfseries \multirow[t]{4}{*}{Caregiver education (SA)}} & 1 & — & — & — & 30 (13.8\%) & 30 (15.8\%) \\ 
 & 2 & — & — & — & 5 (2.3\%) & 5 (2.6\%) \\ 
 & 3 & — & — & — & 1 (0.5\%) & 1 (0.5\%) \\ 
 & — & — & — & — & 181 (83.4\%) & 154 (81.1\%) \\ 
\midrule\addlinespace[2.5pt]
{\bfseries \multirow[t]{4}{*}{Household income (AUS)}} & 1 & 20 (8.6\%) & 19 (8.8\%) & 8 (7.6\%) & — & — \\ 
 & 2 & 126 (54.3\%) & 117 (53.9\%) & 51 (48.6\%) & — & — \\ 
 & 3 & 43 (18.5\%) & 43 (19.8\%) & 26 (24.8\%) & — & — \\ 
 & — & 43 (18.5\%) & 38 (17.5\%) & 20 (19.0\%) & — & — \\ 
\midrule\addlinespace[2.5pt]
{\bfseries \multirow[t]{2}{*}{Household income (SA)}} & Household income (SA), Mean (SD) & — & — & — & 7.81 (3.02) & 7.77 (2.98) \\ 
 & Household income (SA), n & — & — & — & 214 & 188 \\ 
\midrule\addlinespace[2.5pt]
{\bfseries \multirow[t]{2}{*}{Home learning environment (AUS)}} & Home learning environment (AUS; HLE Index), Mean (SD) & 17.84 (10.71) & 17.83 (10.45) & 17.13 (11.39) & — & — \\ 
 & Home learning environment (AUS; HLE Index), n & 232 & 217 & 105 & — & — \\ 
\midrule\addlinespace[2.5pt]
{\bfseries \multirow[t]{8}{*}{Home learning environment (SA)}} & HLE activity frequency (sum), Mean (SD) & — & — & — & 10.13 (3.06) & 12.48 (3.50) \\ 
 & HLE activity frequency (sum), n & — & — & — & 217 & 187 \\ 
 & HLE: books/toys total, Mean (SD) & — & — & — & 2.53 (1.01) & 2.57 (1.07) \\ 
 & HLE: books/toys total, n & — & — & — & 217 & 187 \\ 
 & HLE: time total, Mean (SD) & — & — & — & 4.00 (1.77) & 4.10 (1.84) \\ 
 & HLE: time total, n & — & — & — & 217 & 187 \\ 
 & HLE: unique caregiver types involved, Mean (SD) & — & — & — & 2.26 (1.14) & 1.62 (0.78) \\ 
 & HLE: unique caregiver types involved, n & — & — & — & 214 & 108 \\ 
\bottomrule
\end{tabular*}
\begin{minipage}{\linewidth}
\vspace{.05em}
\textbf{Note.} Summaries are restricted to children with any EF data at each wave (partial EF allowed). In Australia, caregiver education, household income, and the HLE Index are measured once per child and carried across waves; \emph{n} and summary statistics may still differ across T1--T3 because the EF-available sample varies by wave (attrition/partial EF). In South Africa, caregiver education, income, and HLE measures are recorded by wave and summarised only where collected (later-wave cells are NA if not assessed).\\
\end{minipage}

\end{table}

\end{landscape}

\section{Age associations}\label{apx-render-test-re-test-plot}

\begin{figure}[H]

\caption{\label{fig-test-re-test-plot}Executive Function associations
across waves. Note: Standardised scores (z); colour indicates mean age
across available waves}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{EF_network_analysis_files/figure-pdf/fig-test-re-test-plot-1.png}}

}

\end{figure}%

\section{Executive Function across waves}\label{apx-age-ef-wave}

\begin{figure}[H]

\caption{\label{fig-age-ef-wave}Executive Function by age across waves
(z-scored within EF task). Note: Points jittered + transparent; lines
are linear fits with 95\% CI}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{EF_network_analysis_files/figure-pdf/fig-age-ef-wave-1.png}}

}

\end{figure}%

\section{Executive Function scores over time}\label{apx-mean-trend}

\begin{figure}[H]

\caption{\label{fig-mean-trend}\textbf{Mean EF scores over time
(children with repeated EF data).}\\
\emph{Note.} ``EF observed'' at a wave means at least one EF task score
is non-missing. The analytic sample includes only children meeting the
wave-coverage rule: SA = EF observed at both T1 and T2; AU = EF observed
at T1--T3 (``strict'') or at T1 and T2 (``t12'').''}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{EF_network_analysis_files/figure-pdf/fig-mean-trend-1.png}}

}

\end{figure}%

\section{Executive Function individual
trajectories}\label{apx-spaghetti-plot}

\begin{figure}[H]

\caption{\label{fig-spaghetti-plot}\textbf{Individual EF trajectories
over time (children with repeated EF data).}\\
\emph{Note.} ``EF observed'' at a wave means at least one EF task score
is non-missing. The analytic sample includes only children meeting the
wave-coverage rule: SA = EF observed at both T1 and T2; AU = EF observed
at T1--T3 (``strict'') or at T1 and T2 (``t12''). Mean ± 95\% CI is
overlaid. EF scores are z-scored within task (pooled).}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{EF_network_analysis_files/figure-pdf/fig-spaghetti-plot-1.png}}

}

\end{figure}%

\section{Boxplot: Distribution of EF scores across
waves}\label{apx-fig-ef-boxplots-by-wave}

\begin{figure}

\caption{\label{fig-ef-boxplots-by-wave}Executive function scores across
waves in Australia and South Africa. Boxplots show the distribution of
harmonised task scores at each wave, stratified by country.}

\centering{

\pandocbounded{\includegraphics[keepaspectratio]{EF_network_analysis_files/figure-pdf/fig-ef-boxplots-by-wave-1.png}}

}

\end{figure}%

\section{RQ4 Sample sizes for moderation
analysis}\label{apx-tbl-rq4-sample-sizes}

\begin{table}

{\caption{{Sample sizes for socioeconomic moderation analyses by
cohort×wave×group}{\label{tbl-rq4-sample-sizes}}}
\vspace{-20pt}}

\fontsize{8.0pt}{10.0pt}\selectfont
\begin{tabular*}{1\linewidth}{@{\extracolsep{\fill}}ccccc}
\toprule
Cohort & Wave & Group & N & Fit Status\textsuperscript{\textit{1}} \\ 
\midrule\addlinespace[2.5pt]
\multicolumn{5}{>{\raggedright\arraybackslash}m{1\linewidth}}{Income} \\[2.5pt] 
\midrule\addlinespace[2.5pt]
AU & T1 & High & 43 & ✓ \\ 
AU & T1 & Low & 20 & ✓ \\ 
AU & T1 & Middle & 126 & ✓ \\ 
AU & T2 & High & 43 & ✓ \\ 
AU & T2 & Low & 19 & Insufficient n \\ 
AU & T2 & Middle & 117 & ✓ \\ 
AU & T3 & High & 26 & ✓ \\ 
AU & T3 & Low & 8 & Insufficient n \\ 
AU & T3 & Middle & 51 & ✓ \\ 
SA & T1 & High & 52 & ✓ \\ 
SA & T1 & Low & 78 & ✓ \\ 
SA & T1 & Middle & 80 & ✓ \\ 
SA & T2 & High & 47 & ✓ \\ 
SA & T2 & Low & 59 & ✓ \\ 
SA & T2 & Middle & 63 & ✓ \\ 
\midrule\addlinespace[2.5pt]
\multicolumn{5}{>{\raggedright\arraybackslash}m{1\linewidth}}{HLE} \\[2.5pt] 
\midrule\addlinespace[2.5pt]
AU & T1 & High & 86 & ✓ \\ 
AU & T1 & Low & 103 & ✓ \\ 
AU & T2 & High & 91 & ✓ \\ 
AU & T2 & Low & 88 & ✓ \\ 
AU & T3 & High & 42 & ✓ \\ 
AU & T3 & Low & 43 & ✓ \\ 
SA & T1 & High & 103 & ✓ \\ 
SA & T1 & Low & 107 & ✓ \\ 
SA & T2 & High & 85 & ✓ \\ 
SA & T2 & Low & 84 & ✓ \\ 
\bottomrule
\end{tabular*}
\begin{minipage}{\linewidth}
\vspace{.05em}
\textsuperscript{\textit{1}} Minimum n = 20 required for stable network estimation. Groups with insufficient n were excluded from moderation analyses.\\
\end{minipage}

\end{table}

\section{RQ3 results reported on the Fisher z
scale}\label{apx-tbl-rq3-gt-edges-dual}

\begin{table}

{\caption{{Between-cohort differences (edges only) at matched waves (AU
− SA at T1/T2) and difference-in-differences for change from T1 to T2
(ΔAU − ΔSA). Columns show posterior median {[}95\% CrI{]} on the raw
partial-correlation scale (Δr) and Fisher-z scale (Δz = atanh(r)). ROPE
probabilities are computed on Δr:
\(P(|\Delta r| > 0.10)\).}{\label{tbl-rq3-gt-edges-dual}}}
\vspace{-20pt}}

\fontsize{8.0pt}{10.0pt}\selectfont
\begin{tabular*}{1\linewidth}{@{\extracolsep{\fill}}l|cccc}
\toprule
 & \multicolumn{2}{c}{Δr (raw partial correlation)} & \multicolumn{1}{c}{Δz (Fisher atanh scale)} &  \\ 
\cmidrule(lr){2-3} \cmidrule(lr){4-4}
Edge & Median [95\% CrI] & P(|Δr|>0.1) & Median [95\% CrI] & analysis \\ 
\midrule\addlinespace[2.5pt]
\multicolumn{5}{>{\raggedright\arraybackslash}m{1\linewidth}}{Cohort difference (AU − SA) at T1} \\[2.5pt] 
\midrule\addlinespace[2.5pt]
ef\_cogflex - ef\_inhibition & -0.15 [-0.33, 0.03] & 0.72 & -0.16 [-0.34, 0.03] & Main analysis \\ 
ef\_cogflex - ef\_workingmem & 0.13 [-0.05, 0.30] & 0.61 & 0.13 [-0.06, 0.32] & Main analysis \\ 
ef\_inhibition - ef\_workingmem & 0.11 [-0.07, 0.28] & 0.55 & 0.11 [-0.08, 0.30] & Main analysis \\ 
\midrule\addlinespace[2.5pt]
\multicolumn{5}{>{\raggedright\arraybackslash}m{1\linewidth}}{Cohort difference (AU − SA) at T2} \\[2.5pt] 
\midrule\addlinespace[2.5pt]
ef\_cogflex - ef\_inhibition & 0.04 [-0.15, 0.24] & 0.37 & 0.05 [-0.16, 0.25] & Main analysis \\ 
ef\_cogflex - ef\_workingmem & 0.08 [-0.12, 0.27] & 0.45 & 0.08 [-0.12, 0.28] & Main analysis \\ 
ef\_inhibition - ef\_workingmem & 0.13 [-0.05, 0.31] & 0.65 & 0.14 [-0.06, 0.34] & Main analysis \\ 
\midrule\addlinespace[2.5pt]
\multicolumn{5}{>{\raggedright\arraybackslash}m{1\linewidth}}{Difference-in-differences (ΔAU − ΔSA)} \\[2.5pt] 
\midrule\addlinespace[2.5pt]
ef\_cogflex - ef\_inhibition & 0.20 [-0.08, 0.47] & 0.78 & 0.20 [-0.08, 0.48] & Main analysis \\ 
ef\_cogflex - ef\_workingmem & -0.05 [-0.31, 0.21] & 0.48 & -0.05 [-0.33, 0.22] & Main analysis \\ 
ef\_inhibition - ef\_workingmem & 0.03 [-0.24, 0.28] & 0.46 & 0.03 [-0.25, 0.31] & Main analysis \\ 
\bottomrule
\end{tabular*}

\end{table}






\end{document}
